<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <OutputType>Library</OutputType>
	  <TargetFramework>netstandard2.0</TargetFramework>
	  <AssemblyName>Nivaes.App.Cross.SourceGenerator</AssemblyName>
	  <RootNamespace>Nivaes.App.Cross.SourceGenerator</RootNamespace>

	  <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
	  <IncludeBuildOutput>false</IncludeBuildOutput>

	  <LangVersion>latest</LangVersion>
  </PropertyGroup>

	<PropertyGroup>
		<PackageId>Nivaes.App.Cross.SourceGenerator</PackageId>
		<Title>Nivaes App Cross SourceGenerator</Title>
		<Product>Nivaes App Cross SourceGenerator</Product>
		<GeneratePackageOnBuild Condition="'$(Configuration)' == 'Release'">true</GeneratePackageOnBuild>
		<Description>Nivaes App Cross source generator.</Description>
		<PackageTags>Nivaes;app;cross;roslyn</PackageTags>
		<NoPackageAnalysis>true</NoPackageAnalysis>
		<DevelopmentDependency>true</DevelopmentDependency>
	</PropertyGroup>

	<PropertyGroup>
		<PackageReadmeFile>Readme.md</PackageReadmeFile>
	</PropertyGroup>
	
	<ItemGroup>
		<None Include="Images\icon.png" Pack="true" PackagePath="\" />
		<None Include="Docs\Readme.md" Pack="true" PackagePath="\" />
	</ItemGroup>

	<ItemGroup>
		<None Include="$(OutputPath)\$(AssemblyName).dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
	</ItemGroup>
	
	<ItemGroup>
		<PackageReference Include="Microsoft.CodeAnalysis.Analyzers">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>

		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
		
		<PackageReference Update="Roslynator.Analyzers">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	
		<PackageReference Update="SonarAnalyzer.CSharp">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
		</PackageReference>
	</ItemGroup>

</Project>
