<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>$(_CrossiOSTargets);$(_CrossMacCatalystTargets);$(_CrossTvOSTargets)</TargetFrameworks>
		<!--<TargetFrameworks>$(_CrossiOSTargets);$(_CrossMacCatalystTargets)</TargetFrameworks>-->
		<!--<TargetFrameworks>net10.0-tvos</TargetFrameworks>-->
			<Nullable>enable</Nullable>
		<ImplicitUsings>true</ImplicitUsings>

		<!--
      Enable trim analyzers for class libraries.
      To learn more, see: https://learn.microsoft.com/dotnet/core/deploying/trimming/prepare-libraries-for-trimming
    -->
		<!--<IsTrimmable>true</IsTrimmable>-->
		<IsAotCompatible>true</IsAotCompatible>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\Nivaes.App.Cross\Nivaes.App.Cross.csproj" />

		<ProjectReference Include="..\Nivaes.App.Cross.UIKit.SourceGenerator\Nivaes.App.Cross.UIKit.SourceGenerator.csproj">
			<PrivateAssets>runtime; build; native; contentfiles; buildtransitive</PrivateAssets>
			<IncludeAssets>analyzers</IncludeAssets>
			<ExcludeAssets>runtime; build; native; contentfiles; buildtransitive</ExcludeAssets>
		</ProjectReference>
	</ItemGroup>

	<ItemGroup>
		<None Include="Images\icon.png" Pack="true" PackagePath="\" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Nivaes.App.Shared" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Update="Roslynator.Analyzers">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>

		<PackageReference Update="SonarAnalyzer.CSharp">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
		</PackageReference>
	</ItemGroup>
</Project>
