<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>$(_CrossiOSTargets);$(_CrossMacCatalystTargets);$(_CrossTvOSTargets)</TargetFrameworks>
		<AssemblyName>Nivaes.App.Cross.UIKit</AssemblyName>
		<RootNamespace>Nivaes.App.Cross.UIKitLib</RootNamespace>

		<Nullable>enable</Nullable>
		<ImplicitUsings>true</ImplicitUsings>

		<OptimizationPreference>Speed</OptimizationPreference>
		<IsTrimmable>true</IsTrimmable>
		<IsAotCompatible>true</IsAotCompatible>
		<RunAOTAnalysis>true</RunAOTAnalysis>
	</PropertyGroup>

	<PropertyGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">
		<SupportedOSPlatformVersion>$(_SupportedOSPlatformiOSVersion)</SupportedOSPlatformVersion>
		<TargetPlatformVersion>$(_TargetPlatformiOSVersion)</TargetPlatformVersion>
	</PropertyGroup>
	<PropertyGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">
		<SupportedOSPlatformVersion>$(_SupportedOSPlatformMacCatalystVersion)</SupportedOSPlatformVersion>
		<TargetPlatformVersion>$(_TargetPlatformMacCatalystVersion)</TargetPlatformVersion>
	</PropertyGroup>
	<PropertyGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'tvos'">
		<SupportedOSPlatformVersion>$(_SupportedOSPlatformTvOSVersion)</SupportedOSPlatformVersion>
		<TargetPlatformVersion>$(_TargetPlatformTvOSVersion)</TargetPlatformVersion>
	</PropertyGroup>

	<PropertyGroup>
		<PackageId>Nivaes.App.Cross.UIKit</PackageId>
		<Title>Nivaes app Cross UIKit</Title>
		<GeneratePackageOnBuild Condition="'$(Configuration)' == 'Release'">true</GeneratePackageOnBuild>
		<Product>Cross librery for UIKit.</Product>
		<Description>Cross librery for UIKit.</Description>
		<PackageTags>Nivaes;cross;mvvm;UIKit;iOS;MacCatalyst;tvos</PackageTags>
	</PropertyGroup>
	
	<ItemGroup>
		<ProjectReference Include="..\Nivaes.App.Cross\Nivaes.App.Cross.csproj" />

		<ProjectReference Include="..\Nivaes.App.Cross.UIKit.SourceGenerator\Nivaes.App.Cross.UIKit.SourceGenerator.csproj">
			<PrivateAssets>runtime; build; native; contentfiles; buildtransitive</PrivateAssets>
			<IncludeAssets>analyzers</IncludeAssets>
			<ExcludeAssets>runtime; build; native; contentfiles; buildtransitive</ExcludeAssets>
		</ProjectReference>
	</ItemGroup>

	<ItemGroup>
		<None Include="Images\icon.png" Pack="true" PackagePath="\" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Nivaes.App.Shared" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Update="Roslynator.Analyzers">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>

		<PackageReference Update="SonarAnalyzer.CSharp">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
		</PackageReference>
	</ItemGroup>
</Project>
