<Project>
  <ItemGroup>
    <PackageVersion Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.26100.1742" />
    <PackageVersion Include="Microsoft.WindowsAppSDK" Version="1.6.241114003" />
    <PackageVersion Include="AsyncFixer" Version="1.6.0" />
    <PackageVersion Include="Nivaes.App.Shared" Version="0.7.74" />
    <PackageVersion Include="Nivaes.Extensions" Version="2.2.33" />
    <PackageVersion Include="Nivaes.IoC" Version="0.1.8" />
    <PackageVersion Include="OpenTelemetry" Version="1.10.0" />
    <PackageVersion Include="OpenTelemetry.Exporter.Prometheus.HttpListener" Version="1.10.0-beta.1" />
    <PackageVersion Include="Roslynator.Analyzers" Version="4.12.11" />
    <PackageVersion Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="9.0.0" />
    <PackageVersion Include="SonarAnalyzer.CSharp" Version="10.4.0.108396" />
    <PackageVersion Include="Microsoft.CodeAnalysis" Version="4.12.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="4.12.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.Analyzers" Version="3.11.0" />
    <PackageVersion Include="Xamarin.AndroidX.AppCompat" Version="1.7.0.4" />
  </ItemGroup>
</Project>