<Project>
  <ItemGroup>
    <PackageVersion Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.26100.1742" />
    <PackageVersion Include="Microsoft.WindowsAppSDK" Version="1.6.241114003" />
    <PackageVersion Include="AsyncFixer" Version="1.6.0" />
    <PackageVersion Include="Nivaes.App.Shared" Version="0.6.71" />
    <PackageVersion Include="Nivaes.IoC" Version="0.1.2" />
    <PackageVersion Include="Roslynator.Analyzers" Version="4.12.9" />
    <PackageVersion Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="9.0.0" />
    <PackageVersion Include="SonarAnalyzer.CSharp" Version="10.3.0.106239" />
  </ItemGroup>
</Project>