<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>$(_CrossAndroidTargets)</TargetFrameworks>
		<SupportedOSPlatformVersion>$(_SupportedOSPlatformAndroidVersion)</SupportedOSPlatformVersion>
		
		<AssemblyName>Nivaes.App.Cross.Droid</AssemblyName>
		<RootNamespace>Nivaes.App.Cross.Droid</RootNamespace>

		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<OptimizationPreference>Speed</OptimizationPreference>
		<IsTrimmable>true</IsTrimmable>
		<IsAotCompatible>true</IsAotCompatible>
		<RunAOTAnalysis>true</RunAOTAnalysis>
	</PropertyGroup>

	<PropertyGroup>
		<PackageId>Nivaes.App.Cross.Droid</PackageId>
		<Title>Nivaes app Cross Droid</Title>
		<AssemblyName>Nivaes.App.Cross.Droid</AssemblyName>
		<RootNamespace>Nivaes.App.Cross.Droid</RootNamespace>
		<GeneratePackageOnBuild Condition="'$(Configuration)' == 'Release'">true</GeneratePackageOnBuild>
		<Product>Cross librery for android.</Product>
		<Description>Cross librery for Android.</Description>
		<PackageTags>Nivaes;cross;mvvm;android</PackageTags>
		<UserSecretsId>85b02793-bcea-4e02-9c80-ad5ca561205e</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
	  <AndroidJavaSource Remove="Components\Views\Binding\**" />
	  <AndroidLibrary Remove="Components\Views\Binding\**" />
	  <AndroidNativeLibrary Remove="Components\Views\Binding\**" />
	  <Compile Remove="Components\Views\Binding\**" />
	  <EmbeddedResource Remove="Components\Views\Binding\**" />
	  <JavaSourceJar Remove="Components\Views\Binding\**" />
	  <None Remove="Components\Views\Binding\**" />
	  <ProguardConfiguration Remove="Components\Views\Binding\**" />
	  <TransformFile Remove="Components\Views\Binding\**" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="AndHUD" />
		<PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" />
		<PackageReference Include="Nivaes.App.Shared" />
		<PackageReference Include="Xamarin.AndroidX.AppCompat" />
		<PackageReference Include="Xamarin.AndroidX.Leanback" />
		<PackageReference Include="Xamarin.AndroidX.SwipeRefreshLayout" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Nivaes.App.Cross\Nivaes.App.Cross.csproj" />

		<ProjectReference Include="..\Nivaes.App.Cross.Droid.SourceGenerator\Nivaes.App.Cross.Droid.SourceGenerator.csproj">
			<PrivateAssets>runtime; build; native; contentfiles; buildtransitive</PrivateAssets>
			<IncludeAssets>analyzers</IncludeAssets>
			<ExcludeAssets>runtime; build; native; contentfiles; buildtransitive</ExcludeAssets>
		</ProjectReference>

		<ProjectReference Include="..\..\Sources\Nivaes.App.Cross.SourceGenerator\Nivaes.App.Cross.SourceGenerator.csproj">
			<OutputItemType>Analyzer</OutputItemType>
			<ReferenceOutputAssembly>false</ReferenceOutputAssembly>
			<PrivateAssets>runtime; build; native; contentfiles; buildtransitive</PrivateAssets>
			<IncludeAssets>analyzers</IncludeAssets>
			<ExcludeAssets>runtime; build; native; contentfiles; buildtransitive</ExcludeAssets>
		</ProjectReference>
	</ItemGroup>

	<!--<PropertyGroup>
		<EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
		<CompilerGeneratedFilesOutputPath>$(IntermediateOutputPath)Generated</CompilerGeneratedFilesOutputPath>
	</PropertyGroup>-->
	
	<ItemGroup>
		<None Include="Images\icon.png" Pack="true" PackagePath="\" />
	</ItemGroup>

	<ItemGroup>
		<!--<PackageReference Include="Xamarin.AndroidX.AppCompat" />-->
		<!--<PackageReference Include="Xamarin.AndroidX.Fragment" />-->
		<PackageReference Include="Xamarin.AndroidX.Preference" />
		<!--<PackageReference Include="Xamarin.AndroidX.ViewPager" />-->
		<PackageReference Include="Xamarin.Google.Android.Material" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Update="Roslynator.Analyzers">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Update="SonarAnalyzer.CSharp">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
		</PackageReference>
	</ItemGroup>

</Project>
