<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(_CrossAndroidTargets)</TargetFrameworks>
	  <AssemblyName>Nivaes.App.Droid</AssemblyName>
	  <RootNamespace>Nivaes.App.Droid</RootNamespace>
	  
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsTrimmable>true</IsTrimmable>
	<IsAotCompatible>true</IsAotCompatible>
	<RunAOTAnalysis>true</RunAOTAnalysis>
  </PropertyGroup>

	<PropertyGroup>
		<PackageId>Nivaes.App.Cross.Droid</PackageId>
		<Title>Nivaes app Cross Droid</Title>
		<AssemblyName>Nivaes.App.Cross.Droid</AssemblyName>
		<RootNamespace>Nivaes.App.Cross.Droid</RootNamespace>
		<GeneratePackageOnBuild Condition="'$(Configuration)' == 'Release'">true</GeneratePackageOnBuild>
		<Product>Cross librery for android.</Product>
		<Description>Cross librery for Android.</Description>
		<PackageTags>Nivaes;cross;mvvm;android</PackageTags>
	</PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Nivaes.App.Shared" />
    <PackageReference Include="Xamarin.AndroidX.AppCompat" />
    <PackageReference Include="Xamarin.AndroidX.Leanback" />
    <PackageReference Include="Xamarin.AndroidX.SwipeRefreshLayout" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Nivaes.App.Cross\Nivaes.App.Cross.csproj" />

	<ProjectReference Include="..\Nivaes.App.Cross.Droid.SourceGenerator\Nivaes.App.Cross.Droid.SourceGenerator.csproj">
		<PrivateAssets>runtime; build; native; contentfiles; buildtransitive</PrivateAssets>
		<IncludeAssets>analyzers</IncludeAssets>
		<ExcludeAssets>runtime; build; native; contentfiles; buildtransitive</ExcludeAssets>
	</ProjectReference>
	
	 <AndroidResource Include="Resources\**\*.xml" SubType="Designer" Generator="MSBuild:UpdateAndroidResources" />
  </ItemGroup>

	<ItemGroup>
		<None Include="Images\icon.png" Pack="true" PackagePath="\" />
	</ItemGroup>

	<ItemGroup>
		<!--<PackageReference Include="Xamarin.AndroidX.AppCompat" />-->
		<!--<PackageReference Include="Xamarin.AndroidX.Fragment" />-->
		<PackageReference Include="Xamarin.AndroidX.Preference" />
		<!--<PackageReference Include="Xamarin.AndroidX.ViewPager" />-->
		<PackageReference Include="Xamarin.Google.Android.Material" />
	</ItemGroup>

  <ItemGroup>
    <PackageReference Update="Roslynator.Analyzers">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="SonarAnalyzer.CSharp">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Components\Views\Binding\" />
  </ItemGroup>

</Project>
