<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-android</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="nivaes.app.shared" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Nivaes.App.Cross\Nivaes.App.Cross.csproj" />

	  <ProjectReference Include="..\Nivaes.App.Cross.Droid.SourceGenerator\Nivaes.App.Cross.Droid.SourceGenerator.csproj">
		  <PrivateAssets>runtime; build; native; contentfiles; buildtransitive</PrivateAssets>
		  <IncludeAssets>analyzers</IncludeAssets>
		  <ExcludeAssets>runtime; build; native; contentfiles; buildtransitive</ExcludeAssets>
	  </ProjectReference>
  </ItemGroup>

	<ItemGroup>
		<None Include="Images\icon.png" Pack="true" PackagePath="\" />
	</ItemGroup>

  <ItemGroup>
    <PackageReference Update="Roslynator.Analyzers">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="SonarAnalyzer.CSharp">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
