<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net10.0-ios</TargetFrameworks>
		<RuntimeIdentifiers>ios-arm64</RuntimeIdentifiers>
		
		<OutputType>Exe</OutputType>
		<Nullable>enable</Nullable>
		<ImplicitUsings>true</ImplicitUsings>
		<SupportedOSPlatformVersion>13.0</SupportedOSPlatformVersion>

		<!--
      Enable full trimming in Release mode.
      To learn more, see: https://learn.microsoft.com/dotnet/core/deploying/trimming/trimming-options#trimming-granularity
    -->
		<TrimMode Condition="'$(Configuration)' == 'Release'">full</TrimMode>

		<IsPackable>false</IsPackable>
		
		<IsAotCompatible>true</IsAotCompatible>
		<!--<PublishAot>true</PublishAot>-->
	</PropertyGroup>
	<ItemGroup>
	  <AtlasTexture Remove="Components\Views\**" />
	  <Compile Remove="Components\Views\**" />
	  <CoreMLModel Remove="Components\Views\**" />
	  <EmbeddedResource Remove="Components\Views\**" />
	  <ImageAsset Remove="Components\Views\**" />
	  <InterfaceDefinition Remove="Components\Views\**" />
	  <Metal Remove="Components\Views\**" />
	  <None Remove="Components\Views\**" />
	  <SceneKitAsset Remove="Components\Views\**" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Nivaes.App.Shared" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\Nivaes.App.Cross.Sample\Nivaes.App.Cross.Sample.csproj" />
		<ProjectReference Include="..\Nivaes.App.Cross.Sample.UIKit\Nivaes.App.Cross.Sample.UIKit.csproj" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Update="Roslynator.Analyzers">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>
	<ItemGroup>
		<PackageReference Update="SonarAnalyzer.CSharp">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
		</PackageReference>
	</ItemGroup>
	<ItemGroup>
	  <Folder Include="Components\" />
	</ItemGroup>
	<ProjectExtensions><VisualStudio><UserProperties XamarinHotReloadMonoInterpreterErrorInfoBarNivaesAppCrossUIKitiOSSampleHideInfoBar="True" /></VisualStudio></ProjectExtensions>
</Project>
