<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>$(_CrossWindowsTargets)</TargetFrameworks>
		<TargetPlatformMinVersion>$(_CrossWindowsPlatformMinVersion)</TargetPlatformMinVersion>

		<AssemblyName>Nivaes.App.Cross.WinUI</AssemblyName>
		<RootNamespace>Nivaes.App.Cross.WinUI</RootNamespace>

		<!--<RuntimeIdentifiers>win-x64;win-arm64</RuntimeIdentifiers>
		<Platforms>x64;ARM64</Platforms>-->
		<UseWinUI>true</UseWinUI>
		<WinUISDKReferences>false</WinUISDKReferences>
		<AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>

		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<OptimizationPreference>Speed</OptimizationPreference>
		<IsTrimmable>true</IsTrimmable>
		<IsAotCompatible>true</IsAotCompatible>
		<RunAOTAnalysis>true</RunAOTAnalysis>
	</PropertyGroup>

	<PropertyGroup>
		<PackageId>Nivaes.App.Cross.WinUI</PackageId>
		<Title>Nivaes app Cross WinUI</Title>
		
		<GeneratePackageOnBuild Condition="'$(Configuration)' == 'Release'">true</GeneratePackageOnBuild>
		<Product>Cross librery for WinUI3.</Product>
		<Description>Cross librery for WinUI.</Description>
		<PackageTags>Nivaes;cross;mvvm;WinUI;WinUI3</PackageTags>
	</PropertyGroup>
	
	<ItemGroup>
		<!--<PackageReference Include="Microsoft.Windows.SDK.BuildTools" />-->
		<PackageReference Include="CommunityToolkit.WinUI.Collections" />
		<PackageReference Include="Microsoft.WindowsAppSDK" />
		<PackageReference Include="Nivaes.App.Shared" />
	</ItemGroup>
	
	<ItemGroup>
		<ProjectReference Include="..\Nivaes.App.Cross\Nivaes.App.Cross.csproj" />

		<ProjectReference Include="..\Nivaes.App.Cross.WinUI.SourceGenerator\Nivaes.App.Cross.WinUI.SourceGenerator.csproj">
			<PrivateAssets>runtime; build; native; contentfiles; buildtransitive</PrivateAssets>
			<IncludeAssets>analyzers</IncludeAssets>
			<ExcludeAssets>runtime; build; native; contentfiles; buildtransitive</ExcludeAssets>
		</ProjectReference>

		<ProjectReference Include="..\..\Sources\Nivaes.App.Cross.SourceGenerator\Nivaes.App.Cross.SourceGenerator.csproj">
			<OutputItemType>Analyzer</OutputItemType>
			<ReferenceOutputAssembly>false</ReferenceOutputAssembly>
			<PrivateAssets>runtime; build; native; contentfiles; buildtransitive</PrivateAssets>
			<IncludeAssets>analyzers</IncludeAssets>
			<ExcludeAssets>runtime; build; native; contentfiles; buildtransitive</ExcludeAssets>
		</ProjectReference>

	</ItemGroup>
	<ItemGroup>
		<None Include="Images\icon.png" Pack="true" PackagePath="\" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Update="Roslynator.Analyzers">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>
	<ItemGroup>
		<PackageReference Update="SonarAnalyzer.CSharp">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
		</PackageReference>
	</ItemGroup>
	<ItemGroup>
	  <Folder Include="Components\Presenters\Attributes\" />
	</ItemGroup>

</Project>