using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Nivaes.App.Cross.SourceGenerator;

[Generator(LanguageNames.CSharp)]
public class RegisterCombinersGenerator : IIncrementalGenerator
{
    private record struct ConverterInfo(INamedTypeSymbol Type, string? Name, bool Register);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var converters = context.SyntaxProvider.CreateSyntaxProvider(
                    predicate: static (node, _) => node is ClassDeclarationSyntax,
                    transform: static (ctx, _) => GetConverterType(ctx))
            .Where(static t => t is not null)!;

        var rootNamespace = context.AnalyzerConfigOptionsProvider
                .Select(static (options, _) =>
                {
                    options.GlobalOptions.TryGetValue(
                        "build_property.RootNamespace",
                        out var ns);

                    return ns;
                });

        context.RegisterSourceOutput(
            converters.Collect().Combine(rootNamespace),
            Generate
            );
    }

    private static ConverterInfo? GetConverterType(GeneratorSyntaxContext context)
    {
        var classDeclaration = (ClassDeclarationSyntax)context.Node;

        if (context.SemanticModel.GetDeclaredSymbol(classDeclaration) is not INamedTypeSymbol symbol)
            return null;

        if (symbol.IsAbstract || symbol.IsGenericType)
            return null;

        if (!symbol.AllInterfaces.Any(i => i.ToDisplayString() == "Nivaes.App.Cross.ICrossValueCombiner"))
            return null;

        string? name = null;
        bool register = true;

        var attribute = symbol.GetAttributes()
            .FirstOrDefault(a =>
                a.AttributeClass?.ToDisplayString() == "Nivaes.App.Cross.CrossValueCombinerAttribute");

        if (attribute is not null)
        {
            // Busca la propiedad Name
            foreach (var arg in attribute.NamedArguments)
            {
                if (arg.Key == "Name")
                {
                    name = arg.Value.Value as string;
                    break;
                }
                else if (arg.Key == "Register")
                {
                    register = (bool?)arg.Value.Value ?? true;
                }
            }

            // Opcional: si Name también puede venir por constructor
            if (name is null && attribute.ConstructorArguments.Length > 0)
            {
                name = attribute.ConstructorArguments[0].Value as string;
            }
        }

        return new ConverterInfo(symbol, name, register);
    }

    private static void Generate(
    SourceProductionContext context,
    (ImmutableArray<ConverterInfo?> converters, string? rootNamespace) input)
    {
        var types = input.converters
            .Where(x => x != null)
            .Cast<ConverterInfo>()
            .GroupBy(x => x.Type, SymbolEqualityComparer.Default)
            .Select(g => g.First())
            .OrderBy(x => x.Type.Name);

        var rootNamespace = string.IsNullOrWhiteSpace(input.rootNamespace) ? string.Empty : $"namespace {input.rootNamespace};";

        var sourceConverters = string.Join(Environment.NewLine,
            types.Where(combiner => combiner.Register).Select(combiner =>
                {
                    if (string.IsNullOrWhiteSpace(combiner.Name))
                        return $"CombinersContainerHelper.New<{combiner.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}>(services),";
                    else
                        return $"CombinersContainerHelper.New<{combiner.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}>(services, \"{combiner.Name}\"),";
                }
            ));

        string sourceRegisterConverters = string.Empty;
        if (!string.IsNullOrWhiteSpace(sourceConverters))
        {
            sourceRegisterConverters = $@"
                    CombinersContainerHelper.RegisterCombiners(new[]
                    {{
                       {sourceConverters}
                    }});";
        }


        var source = @$"// This file generated for Nivaes.App.Cross.
            // <auto-generated/>
            using System;
            using Nivaes.App.Cross;
            {rootNamespace}
            internal static class GeneratedCombinerExtensions
            {{
                public static IServiceProvider RegisterCombiners(IServiceProvider services)
                {{
                    {sourceRegisterConverters}

                    return services;
                }}
            }}
        ";

        context.AddSource(
            "GeneratedCombinerExtensions.g.cs",
            SourceText.From(source, Encoding.UTF8));
    }
}