<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>$(_CrossiOSTargets);$(_CrossMacCatalystTargets)</TargetFrameworks>
		<Nullable>enable</Nullable>
		<ImplicitUsings>true</ImplicitUsings>

		<!--
      Enable trim analyzers for class libraries.
      To learn more, see: https://learn.microsoft.com/dotnet/core/deploying/trimming/prepare-libraries-for-trimming
    -->
		<IsPackable>false</IsPackable>
		<IsAotCompatible>true</IsAotCompatible>
	</PropertyGroup>
	<ItemGroup>
	  <ImageAsset Remove="Assets.xcassets\ArrowDown.imageset\baseline_keyboard_arrow_down_black_18pt_1x.png" />
	  <ImageAsset Remove="Assets.xcassets\ArrowDown.imageset\baseline_keyboard_arrow_down_black_18pt_2x.png" />
	  <ImageAsset Remove="Assets.xcassets\ArrowDown.imageset\baseline_keyboard_arrow_down_black_18pt_3x.png" />
	  <ImageAsset Remove="Assets.xcassets\ArrowDown.imageset\Contents.json" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Diagnostics" />
		<PackageReference Include="Nivaes.App.Shared" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\sources\Nivaes.App.Cross.UIKit\Nivaes.App.Cross.UIKit.csproj" />
		<ProjectReference Include="..\Nivaes.App.Cross.Sample\Nivaes.App.Cross.Sample.csproj" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Update="Roslynator.Analyzers">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>
	<ItemGroup>
		<PackageReference Update="SonarAnalyzer.CSharp">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
		</PackageReference>
	</ItemGroup>
</Project>
