using System.Collections.Immutable;
using System.Text;
using System.Xml.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Nivaes.App.Cross.SourceGenerator;

[Generator(LanguageNames.CSharp)]
public class RegisterConvertersGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var converters = context.SyntaxProvider.CreateSyntaxProvider(
                    predicate: static (node, _) => node is ClassDeclarationSyntax,
                    transform: static (ctx, _) => GetConverterType(ctx))
            .Where(static t => t is not null)!;

        var rootNamespace = context.AnalyzerConfigOptionsProvider
                .Select(static (options, _) =>
                {
                    options.GlobalOptions.TryGetValue(
                        "build_property.RootNamespace",
                        out var ns);

                    //context.Compilation.AssemblyName

                    return ns;
                });

        //var aa = converters.Collect().Combine(rootNamespace);
        //var bb = aa.Select(k =>
        //{
        //    return k;
        //});

        context.RegisterSourceOutput(
            converters.Collect().Combine(rootNamespace),
            Generate
            );
    }

    //private static bool IsCandidate(SyntaxNode node)
    //{
    //    return node is ClassDeclarationSyntax
    //    {
    //        BaseList.Types.Count: > 0
    //    };
    //}

    private static INamedTypeSymbol? GetConverterType(GeneratorSyntaxContext context)
    {
        var classDeclaration = (ClassDeclarationSyntax)context.Node;

        if (context.SemanticModel.GetDeclaredSymbol(classDeclaration) is not INamedTypeSymbol symbol)
            return null;

        if (symbol.IsAbstract || symbol.IsGenericType)
            return null;

        if (!symbol.AllInterfaces.Any(i => i.ToDisplayString() == "Nivaes.App.Cross.ICrossValueConverter"))
            return null;

        return symbol;
    }

    private static void Generate1(
       SourceProductionContext context,
       ImmutableArray<INamedTypeSymbol?> converters)
    { }

    private static void Generate(
    SourceProductionContext context,
    (ImmutableArray<INamedTypeSymbol?> converters, string? rootNamespace) input)
    {
        var types = input.converters
            .Where(x => x != null)
            .Distinct(SymbolEqualityComparer.Default)
            .Cast<INamedTypeSymbol>()
            .OrderBy(x => x.Name);

        var rootNamespace = input.rootNamespace != null ? $"namespace {input.rootNamespace};" : string.Empty;

        var sourceConverters = string.Join(Environment.NewLine,
            types.Select(converter =>
                $"CrossConvertersManagerHelper.New<{converter.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}>(services),")
            );

        var source = @$"// This file generated for Nivaes.App.Cross.
            // <auto-generated/>
            using System;
            using Nivaes.App.Cross;
            {rootNamespace}
            public static class GeneratedConverterExtensions
            {{
                public static IServiceProvider RegisterConverters(this IServiceProvider services)
                {{
                    CrossConvertersManagerHelper.RegisterComverters(new[]
                    {{
                       {sourceConverters}
                    }});

                    return services;
                }}
            }}
        ";

        context.AddSource(
            "GeneratedConverterExtensions.g.cs",
            SourceText.From(source, Encoding.UTF8));
    }
}