using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Nivaes.App.Cross.SourceGenerator;

[Generator(LanguageNames.CSharp)]
public class RegisterPresenterActionsGenerator : IIncrementalGenerator
{
    private record struct ConverterInfo(INamedTypeSymbol PressentationAttributeType, INamedTypeSymbol PressentationActionType);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var converters = context.SyntaxProvider
        .CreateSyntaxProvider(
            predicate: static (node, _) => node is ClassDeclarationSyntax,
            transform: static (ctx, _) => GetConverterType(ctx))
        .Where(static c => c is not null)!;

        var rootNamespace = context.AnalyzerConfigOptionsProvider
            .Select(static (options, _) =>
            {
                options.GlobalOptions.TryGetValue(
                    "build_property.RootNamespace",
                    out var ns);

                return ns;
            });

        context.RegisterSourceOutput(
            converters.Collect().Combine(rootNamespace),
            Generate);
    }

    private static ConverterInfo? GetConverterType(GeneratorSyntaxContext context)
    {
        var classDeclaration = (ClassDeclarationSyntax)context.Node;

        if (context.SemanticModel.GetDeclaredSymbol(classDeclaration) is not INamedTypeSymbol symbol)
            return null;

        // Ignorar clases abstractas y genéricas
        if (symbol.IsAbstract || symbol.IsGenericType)
            return null;

        var compilation = context.SemanticModel.Compilation;

        var presenterActionInterface =
            compilation.GetTypeByMetadataName("Nivaes.App.Cross.IPressenterAction");

        var presenterActionBase =
            compilation.GetTypeByMetadataName("Nivaes.App.Cross.PressenterAction`1");

        if (presenterActionInterface is null || presenterActionBase is null)
            return null;

        // Debe implementar IPressenterAction
        if (!symbol.AllInterfaces.Any(i =>
            SymbolEqualityComparer.Default.Equals(i, presenterActionInterface)))
        {
            return null;
        }

        // Buscar PressenterAction<TPresentationAttribute> en la jerarquía de herencia
        INamedTypeSymbol? current = symbol;
        INamedTypeSymbol? presentationAttributeType = null;

        while (current is not null)
        {
            if (current.IsGenericType &&
                SymbolEqualityComparer.Default.Equals(
                    current.OriginalDefinition,
                    presenterActionBase))
            {
                presentationAttributeType = current.TypeArguments[0] as INamedTypeSymbol;
                break;
            }

            current = current.BaseType;
        }

        if (presentationAttributeType is null)
            return null;

        return new ConverterInfo(
            presentationAttributeType,
            symbol);
    }

    private static void Generate(
        SourceProductionContext context,
        (ImmutableArray<ConverterInfo?> ressenterActions, string? rootNamespace) input)
    {
        var types = input.ressenterActions
            .Where(x => x != null)
            .Cast<ConverterInfo>()
            //.GroupBy(x => x.Type, SymbolEqualityComparer.Default)
            //.Select(g => g.First());
            .OrderBy(x => x.PressentationActionType.Name);

        var rootNamespace = string.IsNullOrWhiteSpace(input.rootNamespace) ? string.Empty : $"namespace {input.rootNamespace};";

        if (!types.Any())
            return;

        var sourceConverters = string.Join(Environment.NewLine,
            types.Select(type =>
                {
                    return $"PresenterActionsContainerManagerHelper.New<{type.PressentationAttributeType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}, {type.PressentationActionType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}>(services),";
                }
            ));
        var sourceRegisterConverters = $@"
                    PresenterActionsContainerManagerHelper.RegisterPresenterActions(new[]
                    {{
                       {sourceConverters}
                    }});";


        var source = @$"// This file generated for Nivaes.App.Cross.
            // <auto-generated/>
            using System;
            using Nivaes.App.Cross;
            {rootNamespace}
            internal static class GeneratedPresenterActionsExtensions
            {{
                public static IServiceProvider RegisterPresenterActions(this IServiceProvider services)
                {{
                    {sourceRegisterConverters}

                    return services;
                }}
            }}
        ";

        context.AddSource(
            "GeneratedPresenterActionsExtensions.g.cs",
            SourceText.From(source, Encoding.UTF8));
    }
}