<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>$(_CrossMacCatalystTargets)</TargetFramework>
		<OutputType>Exe</OutputType>
		<MacCatalystMinimumVersion>$(_CrossMacCatalystVersion)</MacCatalystMinimumVersion>
		<AssemblyName>Nivaes.App.Cross.Sample.UIKit.MacCatalyst</AssemblyName>
		<RootNamespace>Nivaes.App.Cross.Sample.UIKitLib.MacCatalyst</RootNamespace>

		<Nullable>enable</Nullable>
		<ImplicitUsings>true</ImplicitUsings>

		<ApplicationId>com.nivaes.cross.maccatalyst.sample</ApplicationId>
		<ApplicationTitle>NivaesCross</ApplicationTitle>
		<ApplicationId>com.nivaes.cross.ios.sample</ApplicationId>
		<ValidateXcodeVersion>false</ValidateXcodeVersion>

		<PublishTrimmed>true</PublishTrimmed>
		<TrimMode Condition="'$(Configuration)' == 'Release'">full</TrimMode>
		<IsPackable>false</IsPackable>
		<IsAotCompatible>true</IsAotCompatible>
		<!-- <PublishAot>true</PublishAot> -->
		<!--<StartupObject>Nivaes.App.Cross.Sample.UIKit.MacCatalyst</StartupObject>-->
	</PropertyGroup>

	<PropertyGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">
		<SupportedOSPlatformVersion>$(_SupportedOSPlatformiOSVersion)</SupportedOSPlatformVersion>
		<TargetPlatformVersion>$(_TargetPlatformiOSVersion)</TargetPlatformVersion>
	</PropertyGroup>
	<PropertyGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">
		<SupportedOSPlatformVersion>$(_SupportedOSPlatformMacCatalystVersion)</SupportedOSPlatformVersion>
		<TargetPlatformVersion>$(_TargetPlatformMacCatalystVersion)</TargetPlatformVersion>
	</PropertyGroup>
	<PropertyGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'tvos'">
		<SupportedOSPlatformVersion>$(_SupportedOSPlatformTvOSVersion)</SupportedOSPlatformVersion>
		<TargetPlatformVersion>$(_TargetPlatformTvOSVersion)</TargetPlatformVersion>
	</PropertyGroup>

	<ItemGroup>
		<BundleResource Remove="Resources\home%402x.png" />
		<BundleResource Remove="Resources\home%403x.png" />
		<BundleResource Remove="Resources\home.png" />
		<BundleResource Remove="Resources\ic_tabbar_menu%402x.png" />
		<BundleResource Remove="Resources\ic_tabbar_menu%403x.png" />
		<BundleResource Remove="Resources\ic_tabbar_menu.png" />
		<BundleResource Remove="Resources\settings%402x.png" />
		<BundleResource Remove="Resources\settings%403x.png" />
		<BundleResource Remove="Resources\settings.png" />
	</ItemGroup>
	
	<ItemGroup>
		<ImageAsset Remove="Assets.xcassets\AppIcon.appiconset\Icon1024.png" />
		<ImageAsset Remove="Assets.xcassets\AppIcon.appiconset\Icon128.png" />
		<ImageAsset Remove="Assets.xcassets\AppIcon.appiconset\Icon16.png" />
		<ImageAsset Remove="Assets.xcassets\AppIcon.appiconset\Icon256.png" />
		<ImageAsset Remove="Assets.xcassets\AppIcon.appiconset\Icon32.png" />
		<ImageAsset Remove="Assets.xcassets\AppIcon.appiconset\Icon512.png" />
		<ImageAsset Remove="Assets.xcassets\AppIcon.appiconset\Icon64.png" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Nivaes.App.Cross.Sample.UIKit\Nivaes.App.Cross.Sample.UIKit.csproj" />
		<TrimmerRootAssembly Include="Nivaes.App.Cross.Sample.UIKit" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Sources\Nivaes.App.Cross.SourceGenerator\Nivaes.App.Cross.SourceGenerator.csproj">
			<OutputItemType>Analyzer</OutputItemType>
			<ReferenceOutputAssembly>false</ReferenceOutputAssembly>
			<PrivateAssets>runtime; build; native; contentfiles; buildtransitive</PrivateAssets>
			<IncludeAssets>analyzers</IncludeAssets>
			<ExcludeAssets>runtime; build; native; contentfiles; buildtransitive</ExcludeAssets>
		</ProjectReference>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Update="Roslynator.Analyzers">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>
	<ItemGroup>
		<PackageReference Update="SonarAnalyzer.CSharp">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
		</PackageReference>
	</ItemGroup>
	<ItemGroup>
		<Folder Include="Components\" />
	</ItemGroup>

</Project>
