<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>$(_iOSTargets);$(_MacCatalystTargets)</TargetFrameworks>
		<AssemblyName>Nivaes.App.Cross.Sample.UIKit</AssemblyName>
		<RootNamespace>Nivaes.App.CrossSample.UIKitLib</RootNamespace>

		<Nullable>enable</Nullable>
		<ImplicitUsings>true</ImplicitUsings>

		<IsTrimmable>true</IsTrimmable>
		<VerifyReferenceTrimCompatibility>true</VerifyReferenceTrimCompatibility>
		<IsPackable>false</IsPackable>
		<IsAotCompatible>true</IsAotCompatible>
	</PropertyGroup>
	
	<PropertyGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">
		<SupportedOSPlatformVersion>$(_SupportedOSPlatformiOSVersion)</SupportedOSPlatformVersion>
		<TargetPlatformVersion>$(_TargetPlatformiOSVersion)</TargetPlatformVersion>
	</PropertyGroup>
	<PropertyGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">
		<SupportedOSPlatformVersion>$(_SupportedOSPlatformMacCatalystVersion)</SupportedOSPlatformVersion>
		<TargetPlatformVersion>$(_TargetPlatformMacCatalystVersion)</TargetPlatformVersion>
	</PropertyGroup>
	<PropertyGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'tvos'">
		<SupportedOSPlatformVersion>$(_SupportedOSPlatformTvOSVersion)</SupportedOSPlatformVersion>
		<TargetPlatformVersion>$(_TargetPlatformTvOSVersion)</TargetPlatformVersion>
	</PropertyGroup>
	
	<ItemGroup>
	  <ImageAsset Remove="Assets.xcassets\ArrowDown.imageset\baseline_keyboard_arrow_down_black_18pt_1x.png" />
	  <ImageAsset Remove="Assets.xcassets\ArrowDown.imageset\baseline_keyboard_arrow_down_black_18pt_2x.png" />
	  <ImageAsset Remove="Assets.xcassets\ArrowDown.imageset\baseline_keyboard_arrow_down_black_18pt_3x.png" />
	  <ImageAsset Remove="Assets.xcassets\ArrowDown.imageset\Contents.json" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Diagnostics" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\Sources\Nivaes.App.Cross.UIKit\Nivaes.App.Cross.UIKit.csproj" />
		<ProjectReference Include="..\Nivaes.App.Cross.Sample\Nivaes.App.Cross.Sample.csproj" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Sources\Nivaes.App.Cross.SourceGenerator\Nivaes.App.Cross.SourceGenerator.csproj">
			<OutputItemType>Analyzer</OutputItemType>
			<ReferenceOutputAssembly>false</ReferenceOutputAssembly>
			<PrivateAssets>runtime; build; native; contentfiles; buildtransitive</PrivateAssets>
			<IncludeAssets>analyzers</IncludeAssets>
			<ExcludeAssets>runtime; build; native; contentfiles; buildtransitive</ExcludeAssets>
		</ProjectReference>
	</ItemGroup>
	
	<ItemGroup>
		<PackageReference Update="Roslynator.Analyzers">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>
	<ItemGroup>
		<PackageReference Update="SonarAnalyzer.CSharp">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
		</PackageReference>
	</ItemGroup>
</Project>
