<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>$(_CrossMacOSTargets)</TargetFrameworks>
		<SupportedOSPlatformVersion>$(_SupportedOSPlatformMacOSVersion)</SupportedOSPlatformVersion>
		<AssemblyName>Nivaes.App.Cross.AppKit</AssemblyName>
		<RootNamespace>Nivaes.App.Cross.AppKitLib</RootNamespace>
		
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<OptimizationPreference>Speed</OptimizationPreference>
		<IsTrimmable>true</IsTrimmable>
		<IsAotCompatible>true</IsAotCompatible>
		<RunAOTAnalysis>true</RunAOTAnalysis>
	</PropertyGroup>

	<PropertyGroup>
		<PackageId>Nivaes.App.Cross.AppKit</PackageId>
		<Title>Nivaes app Cross AppKit</Title>
		<GeneratePackageOnBuild Condition="'$(Configuration)' == 'Release'">true</GeneratePackageOnBuild>
		<Product>Cross librery for AppKit.</Product>
		<Description>Cross librery for AppKit.</Description>
		<PackageTags>Nivaes;cross;mvvm;AppKit;macos</PackageTags>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Nivaes.App.Cross\Nivaes.App.Cross.csproj" />

		<ProjectReference Include="..\Nivaes.App.Cross.AppKit.SourceGenerator\Nivaes.App.Cross.AppKit.SourceGenerator.csproj">
			<PrivateAssets>runtime; build; native; contentfiles; buildtransitive</PrivateAssets>
			<IncludeAssets>analyzers</IncludeAssets>
			<ExcludeAssets>runtime; build; native; contentfiles; buildtransitive</ExcludeAssets>
		</ProjectReference>

		<ProjectReference Include="..\..\Sources\Nivaes.App.Cross.SourceGenerator\Nivaes.App.Cross.SourceGenerator.csproj">
			<OutputItemType>Analyzer</OutputItemType>
			<ReferenceOutputAssembly>true</ReferenceOutputAssembly>
			<PrivateAssets>runtime; build; native; contentfiles; buildtransitive</PrivateAssets>
			<IncludeAssets>analyzers</IncludeAssets>
			<ExcludeAssets>runtime; build; native; contentfiles; buildtransitive</ExcludeAssets>
		</ProjectReference>
	</ItemGroup>

	<ItemGroup>
		<None Include="Images\icon.png" Pack="true" PackagePath="\" />
	</ItemGroup>

	<!--<PropertyGroup>
		<EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
		<CompilerGeneratedFilesOutputPath>$(IntermediateOutputPath)Generated</CompilerGeneratedFilesOutputPath>
	</PropertyGroup>-->

	<ItemGroup>
		<PackageReference Update="Roslynator.Analyzers">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>

		<PackageReference Update="SonarAnalyzer.CSharp">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
		</PackageReference>
	</ItemGroup>

</Project>
