// This file has been autogenerated from a class added in the UI designer.

using System.Diagnostics.CodeAnalysis;
using Nivaes.App.Cross.AppKitLib;
using ObjCRuntime;

namespace Nivaes.App.Cross.Sample.AppKitOS.MacOS;

[MvxFromStoryboard("Main")]
[CrossModalPresentation]
[RequiresUnreferencedCode("Bindings require unreferenced code")]
public partial class ModalView : CrossViewController<ModalViewModel>
{
    public ModalView(NativeHandle handle) : base(handle)
    {
        Title = "Modal view";
    }

    public override void ViewDidLoad()
    {
        base.ViewDidLoad();

        var set = CreateBindingSet();
        set.Bind(btnClose).To(vm => vm.CloseCommand);
        set.Apply();
    }
}
