// This file has been autogenerated from a class added in the UI designer.

using System.Diagnostics.CodeAnalysis;
using MvvmCross.Platforms.Mac.Presenters.Attributes;
using MvvmCross.Platforms.Mac.Views;
using Nivaes.App.Cross.AppKit;
using ObjCRuntime;
using Playground.Core.ViewModels;

namespace Playground.Mac
{
    [MvxFromStoryboard("Main")]
    [CrossModalPresentation]
    [RequiresUnreferencedCode("MvxBindings require unreferenced code")]
    public partial class ModalView : MvxViewController<ModalViewModel>
    {
        public ModalView(NativeHandle handle) : base(handle)
        {
            Title = "Modal view";
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            var set = CreateBindingSet();
            set.Bind(btnClose).To(vm => vm.CloseCommand);
            set.Apply();
        }
    }
}
