<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>$(_CrossWindowsTargets)</TargetFrameworks>
		<TargetPlatformMinVersion>$(_TargetPlatformMinVersion)</TargetPlatformMinVersion>
		
		<Platforms>x86;x64;arm64</Platforms>
		<RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>

		<RootNamespace>Nivaes.App.Cross.WinUI3</RootNamespace>

		<EnablePreviewMsixTooling>true</EnablePreviewMsixTooling>
		<GenerateLibraryLayout>true</GenerateLibraryLayout>
		<EnableWindowsTargeting>true</EnableWindowsTargeting>

		<!--<UseAppHost>false</UseAppHost>
		<SelfContained>false</SelfContained>-->
		<IsAotCompatible>true</IsAotCompatible>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.Windows.SDK.BuildTools" />
		<PackageReference Include="Microsoft.WindowsAppSDK" />
		<PackageReference Include="Nivaes.App.Shared" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\Nivaes.App.Cross\Nivaes.App.Cross.csproj" />

		<ProjectReference Include="..\Nivaes.App.Cross.WinUI3.SourceGenerator\Nivaes.App.Cross.WinUI3.SourceGenerator.csproj">
			<PrivateAssets>runtime; build; native; contentfiles; buildtransitive</PrivateAssets>
			<IncludeAssets>analyzers</IncludeAssets>
			<ExcludeAssets>runtime; build; native; contentfiles; buildtransitive</ExcludeAssets>
		</ProjectReference>

	</ItemGroup>
	<ItemGroup>
		<None Include="Images\icon.png" Pack="true" PackagePath="\" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Update="Roslynator.Analyzers">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>
	<ItemGroup>
		<PackageReference Update="SonarAnalyzer.CSharp">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
		</PackageReference>
	</ItemGroup>

</Project>