<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>$(_CrossAndroidTargets)</TargetFrameworks>
		<!--<NoBuild>false</NoBuild>-->
		<BuildInSolution>false</BuildInSolution>
		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
		<IncludeBuildOutput>false</IncludeBuildOutput>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
	</PropertyGroup>

	<!--<PropertyGroup Condition="'$(IsPacking)' == 'true'">
		<NoBuild>true</NoBuild>
	</PropertyGroup>-->

	<!--<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.1" />
	</ItemGroup>-->
	
	<PropertyGroup>
		<!--<OutputType>Library</OutputType>-->
		<TargetFrameworks>$(_CrossTargetFrameworks)</TargetFrameworks>

		<!--<ImplicitUsings>enable</ImplicitUsings>-->
		<!--<Nullable>enable</Nullable>-->

		<SymbolPackageFormat>snupkg</SymbolPackageFormat>

		<PackageId>Nivaes.App.Cross1</PackageId> 
 		<Title>Nivaes App Cross</Title>

		<Product>Nivaes App Cross</Product>
		<Description>Nivaes Cross.</Description>
		<PackageTags>Nivaes;Cross</PackageTags>
		<!--<PackageReadmeFile>Readme.md</PackageReadmeFile>-->

		<IsPackable>true</IsPackable>
		<!--<GeneratePackageOnBuild>true</GeneratePackageOnBuild>-->
		<IncludeBuildOutput>false</IncludeBuildOutput>
	</PropertyGroup>

	<PropertyGroup>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<RepositoryUrl>https://github.com/nivaes/Nivaes.App.Cross</RepositoryUrl>
		<RepositoryType>git</RepositoryType>

		<Product>$(AssemblyName) ($(TargetFramework))</Product>

		<!--<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>-->

		<!--<DebugType>full</DebugType>-->

		<NeutralLanguage>en</NeutralLanguage>
		<VersionPrefix>0.0.1</VersionPrefix>
		<VersionSuffix>-dev-0.2</VersionSuffix>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="NuGet.Build.Tasks.Pack">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>
	
	<ItemGroup>
		<PackageReference Include="Nivaes.App.Shared" />
		<PackageReference Include="Nivaes.Extensions" />
		<PackageReference Include="Nivaes.IoC" />
		<PackageReference Include="OpenTelemetry" />
		<!--<ProjectReference Include="..\..\sources\Nivaes.App.Cross.SourceGenerator\Nivaes.App.Cross.SourceGenerator.csproj">
			<PrivateAssets>runtime; build; native; contentfiles; buildtransitive</PrivateAssets>
			<IncludeAssets>analyzers</IncludeAssets>
			<ExcludeAssets>runtime; build; native; contentfiles; buildtransitive</ExcludeAssets>
		</ProjectReference>-->

		<ProjectReference Include="..\..\sources\Nivaes.App.Cross\Nivaes.App.Cross.csproj" >
			<!--<ReferenceOutputAssembly>false</ReferenceOutputAssembly>
			<Private>false</Private>-->
			<CopyLocal>false</CopyLocal>
			<!--<IncludeOutputs>true</IncludeOutputs>-->
		</ProjectReference>
	</ItemGroup>

	<ItemGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier($(TargetFramework))) == 'macos'">
		<ProjectReference Include="..\..\sources\Nivaes.App.Cross.AppKit\Nivaes.App.Cross.AppKit.csproj" >
			<CopyLocal>false</CopyLocal>
		</ProjectReference>
	</ItemGroup>
	
	<ItemGroup>
		<None Include="..\..\sources\Nivaes.App.Cross\bin\$(Configuration)\$(_CrossCommonTargets)\Nivaes.App.Cross.dll;
					   ..\..\sources\Nivaes.App.Cross\bin\$(Configuration)\$(_CrossCommonTargets)\Nivaes.App.Cross.pdb;
					   ..\..\sources\Nivaes.App.Cross\bin\$(Configuration)\$(_CrossCommonTargets)\Nivaes.App.Cross.xml"
			  Pack="true"
			  PackagePath="lib\$(_CrossMacOSTargets)$(_CrossMacOSVersion)\" />
	
		<None Include="..\..\sources\Nivaes.App.Cross.AppKit\bin\$(Configuration)\$(_CrossMacOSTargets)\Nivaes.App.Cross.AppKit.dll;
					   ..\..\sources\Nivaes.App.Cross.AppKit\bin\$(Configuration)\$(_CrossMacOSTargets)\Nivaes.App.Cross.AppKit.pdb;
					   ..\..\sources\Nivaes.App.Cross.AppKit\bin\$(Configuration)\$(_CrossMacOSTargets)\Nivaes.App.Cross.AppKit.xml"
			  Pack="true"
			  PackagePath="lib\$(_CrossMacOSTargets)$(_CrossMacOSVersion)" />
	</ItemGroup>
	
	<ItemGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier($(TargetFramework))) == 'ios'">
		<ProjectReference Include="..\..\sources\Nivaes.App.Cross.UIKit\Nivaes.App.Cross.UIKit.csproj" />
	</ItemGroup>
	
	<ItemGroup>
		<None Include="..\..\sources\Nivaes.App.Cross\bin\$(Configuration)\$(_CrossCommonTargets)\Nivaes.App.Cross.dll;
					   ..\..\sources\Nivaes.App.Cross\bin\$(Configuration)\$(_CrossCommonTargets)\Nivaes.App.Cross.pdb;
					   ..\..\sources\Nivaes.App.Cross\bin\$(Configuration)\$(_CrossCommonTargets)\Nivaes.App.Cross.xml"
			  Pack="true"
			  PackagePath="lib\$(_CrossiOSTargets)$(_CrossiOSVersion)\" />
		
		<None Include="..\..\sources\Nivaes.App.Cross.UIKit\bin\$(Configuration)\$(_CrossiOSTargets)\Nivaes.App.Cross.UIKit.dll;
					   ..\..\sources\Nivaes.App.Cross.UIKit\bin\$(Configuration)\$(_CrossiOSTargets)\Nivaes.App.Cross.UIKit.pdb;
					   ..\..\sources\Nivaes.App.Cross.UIKit\bin\$(Configuration)\$(_CrossiOSTargets)\Nivaes.App.Cross.UIKit.xml;"
			  Pack="true"
			  PackagePath="lib\$(_CrossiOSTargets)$(_CrossiOSVersion)\"/>
	</ItemGroup>
	
	<ItemGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">
		<ProjectReference Include="..\..\sources\Nivaes.App.Cross.UIKit\Nivaes.App.Cross.UIKit.csproj" />
	</ItemGroup>
	
	<ItemGroup>
		<None Include="..\..\sources\Nivaes.App.Cross\bin\$(Configuration)\$(_CrossCommonTargets)\Nivaes.App.Cross.dll;
					   ..\..\sources\Nivaes.App.Cross\bin\$(Configuration)\$(_CrossCommonTargets)\Nivaes.App.Cross.pdb;
					   ..\..\sources\Nivaes.App.Cross\bin\$(Configuration)\$(_CrossCommonTargets)\Nivaes.App.Cross.xml"
			  Pack="true"
			  PackagePath="lib\$(_CrossMacCatalystTargets)$(_CrossMacCatalystVersion)\" />

		<None Include="..\..\sources\Nivaes.App.Cross.UIKit\bin\$(Configuration)\$(_CrossMacCatalystTargets)\Nivaes.App.Cross.UIKit.dll;
					   ..\..\sources\Nivaes.App.Cross.UIKit\bin\$(Configuration)\$(_CrossMacCatalystTargets)\Nivaes.App.Cross.UIKit.pdb;
					   ..\..\sources\Nivaes.App.Cross.UIKit\bin\$(Configuration)\$(_CrossMacCatalystTargets)\Nivaes.App.Cross.UIKit.xml"
			  Pack="true"
			  PackagePath="lib\$(_CrossMacCatalystTargets)$(_CrossMacCatalystVersion)\" />
	</ItemGroup>
	
	<ItemGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">
		<PackageReference Include="Xamarin.AndroidX.Preference" />
		<ProjectReference Include="..\..\sources\Nivaes.App.Cross.Droid\Nivaes.App.Cross.Droid.csproj" />
	</ItemGroup>
	
	<ItemGroup>
		<None Include="..\..\sources\Nivaes.App.Cross\bin\$(Configuration)\$(_CrossCommonTargets)\Nivaes.App.Cross.dll;
					   ..\..\sources\Nivaes.App.Cross\bin\$(Configuration)\$(_CrossCommonTargets)\Nivaes.App.Cross.pdb;
					   ..\..\sources\Nivaes.App.Cross\bin\$(Configuration)\$(_CrossCommonTargets)\Nivaes.App.Cross.xml"
			  Pack="true"
			  PackagePath="lib\$(_CrossAndroidTargets)$(_CrossAndroidVersion)\" />
	
		<None Include="..\..\sources\Nivaes.App.Cross.Droid\bin\$(Configuration)\$(_CrossAndroidTargets)\Nivaes.App.Cross.Droid.dll;
			           ..\..\sources\Nivaes.App.Cross.Droid\bin\$(Configuration)\$(_CrossAndroidTargets)\Nivaes.App.Cross.Droid.pdb;
			           ..\..\sources\Nivaes.App.Cross.Droid\bin\$(Configuration)\$(_CrossAndroidTargets)\Nivaes.App.Cross.Droid.xml"
			  Pack="true"
			  PackagePath="lib\$(_CrossAndroidTargets)$(_CrossAndroidVersion)\" />
	</ItemGroup>
	
	<ItemGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">
		<ProjectReference Include="..\..\sources\Nivaes.App.Cross.WinUI3\Nivaes.App.Cross.WinUI3.csproj" />
	</ItemGroup>
	
	<ItemGroup>
		<None Include="..\..\sources\Nivaes.App.Cross\bin\$(Configuration)\$(_CrossWindowsTargets)\Nivaes.App.Cross.dll;
					   ..\..\sources\Nivaes.App.Cross\bin\$(Configuration)\$(_CrossWindowsTargets)\Nivaes.App.Cross.pdb;
					   ..\..\sources\Nivaes.App.Cross\bin\$(Configuration)\$(_CrossWindowsTargets)\Nivaes.App.Cross.xml"
			  Pack="true"
			  PackagePath="lib\$(_CrossWindowsTargets)\" />
		
		<None Include="..\..\sources\Nivaes.App.Cross.WinUI3\bin\$(Configuration)\$(_CrossWindowsTargets)\Nivaes.App.Cross.WinUI3.dll;
					   ..\..\sources\Nivaes.App.Cross.WinUI3\bin\$(Configuration)\$(_CrossWindowsTargets)\Nivaes.App.Cross.WinUI3.pdb;
					   ..\..\sources\Nivaes.App.Cross.WinUI3\bin\$(Configuration)\$(_CrossWindowsTargets)\Nivaes.App.Cross.WinUI3.xml"
			  Pack="true"
			  PackagePath="lib\$(_CrossWindowsTargets)\" />
	</ItemGroup>
	
	<ItemGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'tizen'">
	</ItemGroup>
	
	<ItemGroup>
	</ItemGroup>
	  
</Project>