<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>

		<TargetFrameworks>$(_CrossAndroidTargets)</TargetFrameworks>

		<IsPackable>true</IsPackable>
		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>

		<PackageId>Nivaes.App.Cross</PackageId>
		<Version>0.0.1</Version>

		<Title>Nivaes App Cross</Title>
		<Description>Nivaes Cross Platform Library</Description>

		<Authors>Nivaes</Authors>
		<Company>Nivaes</Company>

		<RepositoryUrl>https://github.com/nivaes/Nivaes.App.Cross</RepositoryUrl>
		<RepositoryType>git</RepositoryType>

		<!-- El proyecto empaquetador no genera DLL propia -->
		<IncludeBuildOutput>false</IncludeBuildOutput>

		<!-- Ignorar warning CPM -->
		<NoWarn>$(NoWarn);NU1507</NoWarn>

	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Nivaes.App.Shared" />
		<PackageReference Include="Nivaes.Extensions" />
		<PackageReference Include="Nivaes.IoC" />
		<PackageReference Include="OpenTelemetry" />
	</ItemGroup>

	<Target Name="BuildReferencedProjects" BeforeTargets="Pack">

		<MSBuild Projects="..\..\sources\Nivaes.App.Cross.WinUI3\Nivaes.App.Cross.WinUI3.csproj" Targets="Build" Properties="Configuration=$(Configuration)" />

	</Target>

	<ItemGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier($(TargetFramework))) == 'macos'">
		<ProjectReference Include="..\..\sources\Nivaes.App.Cross.AppKit\Nivaes.App.Cross.AppKit.csproj" />
	</ItemGroup>

	<ItemGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier($(TargetFramework))) == 'ios'">
		<ProjectReference Include="..\..\sources\Nivaes.App.Cross.UIKit\Nivaes.App.Cross.UIKit.csproj" />
	</ItemGroup>

	<ItemGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier($(TargetFramework))) == 'maccatalyst'">
		<ProjectReference Include="..\..\sources\Nivaes.App.Cross.UIKit\Nivaes.App.Cross.UIKit.csproj" />
	</ItemGroup>

	<ItemGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier($(TargetFramework))) == 'android'">
		<ProjectReference Include="..\..\sources\Nivaes.App.Cross.Droid\Nivaes.App.Cross.Droid.csproj" />
	</ItemGroup>

	<ItemGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier($(TargetFramework))) == 'windows'">
		
		<ProjectReference Include="..\..\sources\Nivaes.App.Cross.WinUI3\Nivaes.App.Cross.WinUI3.csproj" />
		
		<None Include="..\..\sources\Nivaes.App.Cross.WinUI3\bin\$(Configuration)\net10.0-windows10.0.22000.0\Nivaes.App.Cross.WinUI3.dll" Pack="true" PackagePath="lib\net10.0-windows10.0.22000.0\" />

		<None Include="..\..\sources\Nivaes.App.Cross.WinUI3\bin\$(Configuration)\net10.0-windows10.0.22000.0\Nivaes.App.Cross.WinUI3.pdb" Condition="Exists('..\..\sources\Nivaes.App.Cross.WinUI3\bin\$(Configuration)\net10.0-windows10.0.22000.0\Nivaes.App.Cross.WinUI3.pdb')" Pack="true" PackagePath="lib\net10.0-windows10.0.22000.0\" />

		<None Include="..\..\sources\Nivaes.App.Cross.WinUI3\bin\$(Configuration)\net10.0-windows10.0.22000.0\Nivaes.App.Cross.WinUI3.xml" Condition="Exists('..\..\sources\Nivaes.App.Cross.WinUI3\bin\$(Configuration)\net10.0-windows10.0.22000.0\Nivaes.App.Cross.WinUI3.xml')" Pack="true" PackagePath="lib\net10.0-windows10.0.22000.0\" />

	</ItemGroup>

	
	
</Project>