<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
		<!--<TargetFrameworks>$(_CrossTargetFrameworks)</TargetFrameworks>-->
		<TargetFrameworks>$(_CrossCommonTargets)</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<TrimMode>full</TrimMode>

		<IsPackable>false</IsPackable>
		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
	</PropertyGroup>

	<PropertyGroup Condition="'$(TargetFramework)'=='$(_CrossAndroidTargets)'">
		<IsAotCompatible>true</IsAotCompatible>
	</PropertyGroup>
	<PropertyGroup Condition="'$(TargetFramework)'=='$(_CrossiOSTargets)'">
		<IsAotCompatible>true</IsAotCompatible>
	</PropertyGroup>
	<PropertyGroup Condition="'$(TargetFramework)'=='$(_CrossMacCatalystTargets)'">
		<IsAotCompatible>true</IsAotCompatible>
	</PropertyGroup>
	<PropertyGroup Condition="'$(TargetFramework)'=='$(_CrossMacOSTargets)'">
		<IsAotCompatible>true</IsAotCompatible>
	</PropertyGroup>
	<PropertyGroup Condition="'$(TargetFramework)'=='$(_CrossTvOSTargets)'">
		<IsAotCompatible>true</IsAotCompatible>
	</PropertyGroup>

	<ItemGroup>
		<None Include="Images\icon.png" Pack="true" PackagePath="\" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Logging" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" />
		<PackageReference Include="Nivaes.App.Shared" />
		<PackageReference Include="OpenTelemetry" />
		<PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
		<PackageReference Include="OpenTelemetry.Extensions.Hosting" />
		<PackageReference Include="OpenTelemetry.Instrumentation.Http" />
		<PackageReference Include="Serilog.Extensions.Logging" />
		<PackageReference Include="Serilog.Sinks.Trace" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\sources\Nivaes.App.Cross\Nivaes.App.Cross.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Update="Roslynator.Analyzers">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>

		<PackageReference Update="SonarAnalyzer.CSharp">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
		</PackageReference>
	</ItemGroup>

</Project>
