<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>

		<AssemblyName>Nivaes.App.Cross.WinUI.SourceGenerator</AssemblyName>
		<RootNamespace>Nivaes.App.Cross.WinUI.SourceGenerator</RootNamespace>

		<IncludeBuildOutput>false</IncludeBuildOutput>
		<EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
		<IsRoslynComponent>true</IsRoslynComponent>
		<PublishAot>false</PublishAot>

		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<PropertyGroup>
		<PackageId>Nivaes.App.Cross.WinUI.SourceGenerator</PackageId>
		<Title>Nivaes WinUI SourceGenerator</Title>
		<Product>Nivaes App Cross WinUI SourceGenerator</Product>
		<GeneratePackageOnBuild Condition="'$(Configuration)' == 'Release'">true</GeneratePackageOnBuild>
		<Description>Nivaes App Cross WinUI source generator.</Description>
		<PackageTags>Nivaes;app;cross;WinUI;roslyn</PackageTags>
		<NoPackageAnalysis>true</NoPackageAnalysis>
		<DevelopmentDependency>true</DevelopmentDependency>
	</PropertyGroup>

	<ItemGroup>
		<None Include="Images\icon.png" Pack="true" PackagePath="\" />
		<None Include="Docs\Readme.md" Pack="true" PackagePath="\"/>
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Components\" />
	</ItemGroup>

	<ItemGroup>
		<None Include="$(OutputPath)\$(AssemblyName).dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.CodeAnalysis.Analyzers">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>

		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" />

		<PackageReference Update="Roslynator.Analyzers">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>

		<PackageReference Update="SonarAnalyzer.CSharp">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
		</PackageReference>
	</ItemGroup>

</Project>
