name: WinUI setup
description: Configures .NET and WinUI SDK for WinUI builds

inputs:
  global-json-file:
    description: Path to global.json
    required: false
    default: global.json

runs:
  using: composite

  steps:
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v5
      with:
        global-json-file: ${{ inputs.global-json-file }}
        # cache: true
        # cache-dependency-path: |
        #   **/packages.lock.json
      #   source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      # env:
      #   NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v3
