<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
	  <AssemblyName>Nivaes.App.Cross.Sample.PWA</AssemblyName>
	  <RootNamespace>Nivaes.App.Cross.Sample.PWA</RootNamespace>
	  
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Orquestation\Nivaes.App.Cross.AppHost\Nivaes.App.Cross.ServiceDefaults\Nivaes.App.Cross.ServiceDefaults.csproj" />
    <ProjectReference Include="..\Nivaes.App.Cross.Sample.PWA.Client\Nivaes.App.Cross.Sample.PWA.Client.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" />
  </ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Sources\Nivaes.App.Cross.SourceGenerator\Nivaes.App.Cross.SourceGenerator.csproj">
			<OutputItemType>Analyzer</OutputItemType>
			<ReferenceOutputAssembly>true</ReferenceOutputAssembly>
			<PrivateAssets>runtime; build; native; contentfiles; buildtransitive</PrivateAssets>
			<IncludeAssets>analyzers</IncludeAssets>
			<ExcludeAssets>runtime; build; native; contentfiles; buildtransitive</ExcludeAssets>
		</ProjectReference>
	</ItemGroup>
	
</Project>
