<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>$(_CrossAndroidTargets)</TargetFramework>
		<!--<Platforms>x64;arm64</Platforms>-->
		<!--<RuntimeIdentifiers>android-x64;android-arm64</RuntimeIdentifiers>-->
		
		<SupportedOSPlatformVersion>23</SupportedOSPlatformVersion>
		<OutputType>Exe</OutputType>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<ApplicationId>com.nivaes.app.sample.cross</ApplicationId>
		<ApplicationVersion>1</ApplicationVersion>
		<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
		<!--		
      Enables trim analyzers and full trimming during Release mode.
      To learn more, see: https://learn.microsoft.com/dotnet/core/deploying/trimming/trimming-options#trimming-granularity
    -->
		<!--<IsPackable>false</IsPackable>-->
		<!--<GeneratePackageOnBuild>false</GeneratePackageOnBuild>-->

		<RunAOTAnalysis>true</RunAOTAnalysis>
		<IsAotCompatible>true</IsAotCompatible>

		<!--<PublishAot Condition="'$(Configuration)' == 'Release'">true</PublishAot>-->
		<!--<AndroidFastDeploymentType>true</AndroidFastDeploymentType>-->
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Diagnostics" />
		<PackageReference Include="Nivaes.App.Shared" />
		<!--<PackageReference Include="Xamarin.Android.Glide" />-->
		<PackageReference Include="Xamarin.Android.Glide" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\sources\Nivaes.App.Cross.Droid\Nivaes.App.Cross.Droid.csproj" />
		<ProjectReference Include="..\Nivaes.App.Cross.Sample\Nivaes.App.Cross.Sample.csproj" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Update="Roslynator.Analyzers">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>
	<ItemGroup>
		<PackageReference Update="SonarAnalyzer.CSharp">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
		</PackageReference>
	</ItemGroup>
</Project>