<Project Sdk="Aspire.AppHost.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>eb23fdfc-d577-41cc-93fa-e162e12bc013</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <!--<ProjectReference Include="..\..\..\sources\Nivaes.App.Cross.WinUI\Nivaes.App.Cross.WinUI.csproj" />-->
  </ItemGroup>

</Project>
