<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
		<TargetFramework>net9.0</TargetFramework>
		<!--<ImplicitUsings>enable</ImplicitUsings>-->

		<AssemblyName>Nivaes.App.Cross</AssemblyName>
		<RootNamespace>Nivaes.App.Cross</RootNamespace>

		<IsAotCompatible>true</IsAotCompatible>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Nivaes.App.Shared" />
		<PackageReference Include="Nivaes.Extensions" />
		<PackageReference Include="Nivaes.IoC" />
		<PackageReference Include="OpenTelemetry" />
		<PackageReference Include="OpenTelemetry.Exporter.Prometheus.HttpListener" />

		<ProjectReference Include="..\Nivaes.App.Cross.SourceGenerator\Nivaes.App.Cross.SourceGenerator.csproj">
			<PrivateAssets>runtime; build; native; contentfiles; buildtransitive</PrivateAssets>
			<IncludeAssets>analyzers</IncludeAssets>
			<ExcludeAssets>runtime; build; native; contentfiles; buildtransitive</ExcludeAssets>
		</ProjectReference>
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="Nivaes.App.Cross.Droid" />
		<InternalsVisibleTo Include="Nivaes.App.Cross.UIKit" />
		<InternalsVisibleTo Include="Nivaes.App.Cross.AppKit" />
		<InternalsVisibleTo Include="Nivaes.App.Cross.WinUI" />
	</ItemGroup>

	<PropertyGroup>
		<PackageReadmeFile>Readme.md</PackageReadmeFile>
	</PropertyGroup>
	
	<ItemGroup>
		<None Include="Images\icon.png" Pack="true" PackagePath="\" />
		<None Include="Docs\Readme.md" Pack="true" PackagePath="\" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Update="Roslynator.Analyzers">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>

		<PackageReference Update="SonarAnalyzer.CSharp">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
		</PackageReference>
	</ItemGroup>

</Project>
