<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
		<TargetFrameworks>$(_CrossCommonTargets)</TargetFrameworks>
		<AssemblyName>Nivaes.App.Cross</AssemblyName>
		<RootNamespace>Nivaes.App.Cross</RootNamespace>	
	</PropertyGroup>

	<PropertyGroup>
		<PackageId>Nivaes.App.Cross.Core</PackageId>
		<Title>Nivaes app Cross core</Title>
		<GeneratePackageOnBuild Condition="'$(Configuration)' == 'Release'">true</GeneratePackageOnBuild>
		<Product>Cross librery core.</Product>
		<Description>Cross librery core.</Description>
		<PackageTags>Nivaes;cross</PackageTags>
	</PropertyGroup>
		
	<PropertyGroup>
		<MyAppName>MiApp</MyAppName>
	</PropertyGroup>
		
	<PropertyGroup Condition="'$(TargetFramework)'=='$(_CrossAndroidTargets)'">
		<IsAotCompatible>true</IsAotCompatible>
	</PropertyGroup>
	<PropertyGroup Condition="'$(TargetFramework)'=='$(_CrossiOSTargets)'">
		<IsAotCompatible>true</IsAotCompatible>
	</PropertyGroup>
	<PropertyGroup Condition="'$(TargetFramework)'=='$(_CrossMacCatalystTargets)'">
		<IsAotCompatible>true</IsAotCompatible>
	</PropertyGroup>
	<PropertyGroup Condition="'$(TargetFramework)'=='$(_CrossMacOSTargets)'">
		<IsAotCompatible>true</IsAotCompatible>
	</PropertyGroup>
	<PropertyGroup Condition="'$(TargetFramework)'=='$(_CrossTvOSTargets)'">
		<IsAotCompatible>true</IsAotCompatible>
	</PropertyGroup>
	<ItemGroup>
	  <Compile Remove="Components\Observabilidad\**" />
	  <EmbeddedResource Remove="Components\Observabilidad\**" />
	  <None Remove="Components\Observabilidad\**" />
	</ItemGroup>
	
	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
		<PackageReference Include="Nivaes.App.Secrets" />
		<PackageReference Include="Nivaes.App.Shared" />
		<PackageReference Include="Nivaes.Extensions" />
		<PackageReference Include="Nivaes.IoC" />
		<PackageReference Include="OpenTelemetry" />
		<ProjectReference Include="..\Nivaes.App.Cross.SourceGenerator\Nivaes.App.Cross.SourceGenerator.csproj">
			<OutputItemType>Analyzer</OutputItemType>
			<ReferenceOutputAssembly>true</ReferenceOutputAssembly>
			<PrivateAssets>runtime; build; native; contentfiles; buildtransitive</PrivateAssets>
			<IncludeAssets>analyzers</IncludeAssets>
			<ExcludeAssets>runtime; build; native; contentfiles; buildtransitive</ExcludeAssets>
		</ProjectReference>
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="Nivaes.App.Cross.Droid" />
		<InternalsVisibleTo Include="Nivaes.App.Cross.UIKit" />
		<InternalsVisibleTo Include="Nivaes.App.Cross.AppKit" />
		<InternalsVisibleTo Include="Nivaes.App.Cross.WinUI" />
		<InternalsVisibleTo Include="Nivaes.App.Cross.Web" />
	</ItemGroup>

	<PropertyGroup>
		<PackageReadmeFile>Readme.md</PackageReadmeFile>
	</PropertyGroup>
	
	<ItemGroup>
		<None Include="Images\icon.png" Pack="true" PackagePath="\" />
		<None Include="Docs\Readme.md" Pack="true" PackagePath="\" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Update="Roslynator.Analyzers">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>

		<PackageReference Update="SonarAnalyzer.CSharp">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
		</PackageReference>
	</ItemGroup>
</Project>
