name: Xcode setup
description: Configures .NET and Xcode for macos and ios builds

inputs:
  global-json-file:
    description: Path to global.json
    required: false
    default: global.json
#   repository_owner:
#     description: Repository outner
#     required: true
# secrets:
#   github_token:
#     description: github token
#     required: true

runs:
  using: composite

  steps:
    - name: Install xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v5
      with:
        global-json-file: ${{ inputs.global-json-file }}
        workloads: ios, maccatalyst, tvos, macos
        # cache: true
        # cache-dependency-path: |
        #   **/packages.lock.json
      #   source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      # env:
      #   NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    # - name: Cache workloads
    #   id: workload-cache
    #   uses: actions/cache@v4
    #   with:
    #     path: |
    #       ~/.dotnet
    #       ~/.nuget/packages
    #     key: workloads-${{ runner.os }}-${{ hashFiles('global.json') }}
    #     restore-keys: |
    #       workloads-${{ runner.os }}-

    # - name: Install workload
    #   if: steps.workload-cache.outputs.cache-hit != 'true'
    #   shell: bash
    #   run: |
    #      dotnet workload install android ios maccatalyst macos tvos --version 10.0.103
