<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net10.0</TargetFrameworks>
		<AssemblyName>Nivaes.App.Cross.PWA</AssemblyName>
		<RootNamespace>Nivaes.App.Cross.PWA</RootNamespace>
		
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<OptimizationPreference>Speed</OptimizationPreference>
		<IsTrimmable>true</IsTrimmable>
		<IsAotCompatible>true</IsAotCompatible>
		<RunAOTAnalysis>true</RunAOTAnalysis>
	</PropertyGroup>

	<PropertyGroup>
		<PackageId>Nivaes.App.Cross.PWA</PackageId>
		<Title>Nivaes app Cross PWA</Title>
		<GeneratePackageOnBuild Condition="'$(Configuration)' == 'Release'">true</GeneratePackageOnBuild>
		<Product>Cross librery for PWA.</Product>
		<Description>Cross librery for PWA.</Description>
		<PackageTags>Nivaes;cross;mvvm;PWA</PackageTags>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Nivaes.App.Cross\Nivaes.App.Cross.csproj" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Nivaes.App.Cross.PWA.SourceGenerator\Nivaes.App.Cross.PWA.SourceGenerator.csproj">
			<PrivateAssets>runtime; build; native; contentfiles; buildtransitive</PrivateAssets>
			<IncludeAssets>analyzers</IncludeAssets>
			<ExcludeAssets>runtime; build; native; contentfiles; buildtransitive</ExcludeAssets>
		</ProjectReference>
	</ItemGroup>

</Project>
