<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net9.0-ios;net9.0-maccatalyst</TargetFrameworks>
    <Nullable>enable</Nullable>
    <ImplicitUsings>true</ImplicitUsings>

    <!--
      Enable trim analyzers for class libraries.
      To learn more, see: https://learn.microsoft.com/dotnet/core/deploying/trimming/prepare-libraries-for-trimming
    -->
    <IsTrimmable>true</IsTrimmable>
  </PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\sources\Nivaes.App.Cross.iOS\Nivaes.App.Cross.iOS.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Components\" />
	</ItemGroup>
</Project>
