name: CI

on:
  push:
    branches-ignore:
    - 'release/v**'
    paths-ignore:
    - '**/*.md'
    - '**/*.sln'
  pull_request:
    #types: [opened, synchronize, reopened]
    types: [synchronize]
    paths-ignore:
    - '**/*.md'
    - '**/*.sln'

permissions:
  contents: read
  packages: read

jobs:
  build-app-cross:
    runs-on: ubuntu-latest

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Checkout
      uses: actions/checkout@v5

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v5
      with:
        global-json-file: ./global.json
        source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Restore Dependencies
      run: |
          dotnet restore sources/Nivaes.App.Cross
          dotnet restore sources/Nivaes.App.Cross.SourceGenerator

    - name: Build
      run: |
          dotnet build sources/Nivaes.App.Cross --configuration Release --no-restore
          dotnet build sources/Nivaes.App.Cross.SourceGenerator --configuration Release --no-restore

    - name: Test
      run: |
          dotnet test sources/Nivaes.App.Cross --configuration Release --no-build --verbosity normal --no-restore
          dotnet test sources/Nivaes.App.Cross.SourceGenerator --configuration Release --no-build --verbosity normal --no-restore

  build-app-cross-android:
    needs: build-app-cross
    runs-on: ubuntu-latest

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Checkout
      uses: actions/checkout@v5

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v5
      with:
        global-json-file: ./global.json
        source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Install workload
      run: |
        dotnet workload install android

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Restore Dependencies
      run: |
          dotnet restore sources/Nivaes.App.Cross.Droid
          dotnet restore sources/Nivaes.App.Cross.Droid.SourceGenerator

    - name: Build
      run: |
          dotnet build sources/Nivaes.App.Cross.Droid --configuration Release --no-restore
          dotnet build sources/Nivaes.App.Cross.Droid.SourceGenerator --configuration Release --no-restore

    - name: Test
      run: |
          dotnet test sources/Nivaes.App.Cross.Droid --configuration Release --no-build --verbosity normal --no-restore
          dotnet test sources/Nivaes.App.Cross.Droid.SourceGenerator --configuration Release --no-build --verbosity normal --no-restore

  build-app-cross-ios:
    needs: build-app-cross
    # runs-on: windows-latest
    runs-on: [self-hosted,Windows,X64]


    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Checkout
      uses: actions/checkout@v5

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v5
      with:
        global-json-file: ./global.json
        source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Install workload
      run: |
        dotnet workload install ios

    - name: Restore Dependencies
      run: |
          dotnet restore sources/Nivaes.App.Cross.UIKit
          dotnet restore sources/Nivaes.App.Cross.UIKit.SourceGenerator

    - name: Build
      run: |
          dotnet build sources/Nivaes.App.Cross.UIKit --configuration Release --no-restore
          dotnet build sources/Nivaes.App.Cross.UIKit.SourceGenerator --configuration Release --no-restore

    - name: Test
      run: |
          dotnet test sources/Nivaes.App.Cross.UIKit --configuration Release --no-build --verbosity normal --no-restore
          dotnet test sources/Nivaes.App.Cross.UIKit.SourceGenerator --configuration Release --no-build --verbosity normal --no-restore

 
  # publish-identity-client-mac:
  #   needs: build-identity-client
  #   runs-on: macos-latest
  #   runs-on: windows-latest

  #   steps:
  #   - name: Dump GitHub context
  #     env:
  #       GITHUB_CONTEXT: ${{ toJson(github) }}
  #     run: echo "$GITHUB_CONTEXT"

  #   - name: Checkout
  #     uses: actions/checkout@v4

  #   - name: Setup .NET Core
  #     uses: actions/setup-dotnet@v4
  #     with:
  #       global-json-file: ./global.json
  #       source-url: https://nuget.pkg.github.com/Nivaes/index.json
  #     env:
  #       NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

  #   - uses: maxim-lobanov/setup-xcode@v1
  #     with:
  #       xcode-version: latest-stable

  #   - name: Install workload
  #     run: |
  #       dotnet workload install mobile-librarybuilder

  #   - name: Restore Dependencies
  #     run: |
  #      dotnet restore Nivaes.App.Core.iOS
  #      dotnet restore Nivaes.App.Identity.iOS
  #      dotnet restore Nivaes.App.Identity.iOS.Sample

  #   - name: Build
  #     run: |
  #      dotnet build Nivaes.App.Core.iOS --configuration Release --no-restore --framework net9.0-ios 
  #      dotnet build Nivaes.App.Identity.iOS --configuration Release --no-restore --framework net9.0-ios 
  #      dotnet build Nivaes.App.Identity.iOS.Sample --configuration Release --no-restore --framework net9.0-ios 

  #   - name: Publish ios
  #     run: |
  #       dotnet publish Nivaes.App.Identity.iOS.Sample --configuration Release --no-restore --no-restore --framework net9.0-ios --runtime ios-arm64

  #   - name: Publish maccatalyst
  #     run: |
  #       dotnet publish Nivaes.App.Identity.iOS.Sample --configuration Release --no-restore --no-restore --framework net9.0-maccatalyst --runtime ios-arm64

  # publish-identity-client-winui:
  #   needs: build-identity-client
  #   runs-on: windows-latest
    
  #   steps:
  #   - name: Dump GitHub context
  #     env:
  #       GITHUB_CONTEXT: ${{ toJson(github) }}
  #     run: echo "$GITHUB_CONTEXT"

  #   - name: Checkout
  #     uses: actions/checkout@v4

  #   - name: Setup .NET Core
  #     uses: actions/setup-dotnet@v4
  #     with:
  #       global-json-file: ./global.json
  #       source-url: https://nuget.pkg.github.com/Nivaes/index.json
  #     env:
  #       NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

  #   - uses: microsoft/setup-msbuild@v2
  #     name: Setup msbuild

  #   - name: Restore Dependencies
  #     run: |
  #      dotnet restore Nivaes.App.Core.WinUI
  #      dotnet restore Nivaes.App.Identity.WinUI
  #      dotnet restore Nivaes.App.Identity.WinUI.Sample

  #   - name: Build
  #     run: |
  #      dotnet build Nivaes.App.Core.WinUI --configuration Release --no-restore --runtime win-x64
  #      dotnet build Nivaes.App.Identity.WinUI --configuration Release --no-restore --runtime win-x64
  #      dotnet build Nivaes.App.Identity.WinUI.Sample --configuration Release --no-restore --runtime win-x64

  #   - name: Publish
  #     run: |
  #       dotnet publish Nivaes.App.Identity.WinUI.Sample --configuration Release --no-restore --runtime win-x64
  #       dotnet publish ${{ env.PROJECT_PATH }} -c Release -r win-$($runtimeIdentifier.ToLower()) /p:GITHUB_ACTIONS=true -p:Platform=${{ matrix.platform }} --self-contained ${{ env.PUBLISH_SELF_CONTAINED }} -p:PublishSingleFile=${{ env.PUBLISH_SINGLE_FILE }} -p:PublishReadyToRun=${{ env.PUBLISH_READY_TO_RUN }} -p:PublishTrimmed=${{ env.PUBLISH_TRIMMED }} -p:TrimMode=${{ env.PUBLISH_TRIM_MODE }} -p:PublishAot=${{ env.PUBLISH_AOT }} --output ${{ env.PUBLISH_OUTPUT_FOLDER }}/${{ matrix.platform }}

