name: CI

on:
  push:
    branches-ignore:
    - 'release/**'
    paths-ignore:
    - '**/*.md'
    - 'Samples/**'
  pull_request:
    types: [opened, synchronize, reopened] 
    paths-ignore:
    - '**/*.md'
    - 'Samples/**'

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET Core 3.1.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Setup .NET Core 5.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        source-url: https://nuget.pkg.github.com/Nivaes/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Setup .NET Core 6.0.x
      uses: actions/setup-dotnet@v1 
      with:
        dotnet-version: 6.0.100-preview.6.21354.2

    - name: Build.App.Cross
      run: dotnet build ./Nivaes.App.Cross/ --configuration Release

    #- name: Test
    #  run: dotnet test --configuration Release --no-build --verbosity normal

  build-Android:
    needs: build
    runs-on: windows-2019
    #runs-on: ubuntu-20.04

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Checkout
      uses: actions/checkout@v2

    #- name: Setup .NET Core 3.1.x
    #  uses: actions/setup-dotnet@v1
    #  with:
    #    dotnet-version: 3.1.x

    #- name: Setup .NET Core 5.0.x
    #  uses: actions/setup-dotnet@v1
    #  with:
    #    dotnet-version: 5.0.x
    #    source-url: https://nuget.pkg.github.com/Nivaes/index.json
    #  env:
    #    NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    #- name: Setup .NET Core 6.0.x
    #  uses: actions/setup-dotnet@v1
    #  with:
    #    dotnet-version: 6.0.100-preview.44.21255.9

    - name: Setup .NET Core 6.0.x
      run: |
        Invoke-WebRequest -Uri "https://dot.net/v1/dotnet-install.ps1" -OutFile dotnet-install.ps1
        .\dotnet-install.ps1 -Version 6.0.100-preview.6.21354.2 -InstallDir "$env:ProgramFiles\dotnet\" -Verbose
        dotnet --list-sdks

    #- name: Install Android Workloads
    #  shell: pwsh
    #  run: |
    #    dotnet tool install --global boots
    #    boots https://dl.internalx.com/vsts-devdiv/Xamarin.Android/public/net6/4677238/main/19703962615d9170a6b289ab90e566d187bc6c3b/Microsoft.NET.Workload.Android.11.0.200.226.msi
    #    boots https://download.visualstudio.microsoft.com/download/pr/a80cea37-dc44-4757-8eb7-d9f2607c4c2d/4a7c797bab5caa5a618113b72046a560/microsoft-jdk-11.0.11.9.1-windows-x64.msi

    - name: Install Maui
      shell: pwsh
      run: |
        dotnet tool update --global redth.net.maui.check --version 0.6.0-pre01 --add-source https://api.nuget.org/v3/index.json
        #maui-check --ci --non-interactive --fix --skip androidsdk --skip xcode --skip vswin --skip vsmac --main


    - name: Build App.Cross
      run: dotnet build ./Nivaes.App.Cross/ --framework netstandard2.1 --configuration Release

    - name: Build App.Cross.Droid
      run: dotnet build ./Nivaes.App.Cross.Droid/ --configuration Release

  build-MacOs:
    needs: build
    runs-on: macos-10.15

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET Core 3.1.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    #- name: Setup .NET Core 5.0.x
    #  uses: actions/setup-dotnet@v1
    #  with:
    #    dotnet-version: 5.0.x
    #    source-url: https://nuget.pkg.github.com/Nivaes/index.json
    #  env:
    #    NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    #- name: Setup .NET Core 6.0.x
    #  uses: actions/setup-dotnet@v1
    #  with:
    #    dotnet-version: 6.0.100-preview.44.21255.9

    - name: Install .NET Core 6.0.x
      run: |
        export PATH="/usr/local/share/dotnet/:~/.dotnet/tools:$PATH" 
        curl -L https://raw.githubusercontent.com/dotnet/install-scripts/7a9d5dcab92cf131fc2d8977052f8c2c2d540e22/src/dotnet-install.sh > dotnet-install.sh 
        sh dotnet-install.sh --version 6.0.100-preview.6.21354.2 --install-dir $DOTNET_ROOT --verbose 
        dotnet --list-sdks
        echo "##vso[task.setvariable variable=PATH]$PATH"

    #- name: Install iOS Workloads
    #  run: |
    #    dotnet tool install --global boots
    #    boots https://bosstoragemirror.azureedge.net/wrench/main/405441f544149677e420c9c0f8a8788f7bcbbeb3/4673591/package/notarized/Microsoft.iOS.Bundle.14.5.100-ci.main.620.pkg
    #    boots https://bosstoragemirror.azureedge.net/wrench/main/405441f544149677e420c9c0f8a8788f7bcbbeb3/4673591/package/notarized/Microsoft.macOS.Bundle.11.3.100-ci.main.620.pkg
    #    boots https://bosstoragemirror.azureedge.net/wrench/main/405441f544149677e420c9c0f8a8788f7bcbbeb3/4673591/package/notarized/Microsoft.MacCatalyst.Bundle.14.5.100-ci.main.620.pkg

    - name: Install Maui
      shell: pwsh
      run: |
        dotnet tool update --global redth.net.maui.check --version 0.6.0-pre01 --add-source https://api.nuget.org/v3/index.json
        maui-check --ci --non-interactive --fix --skip androidsdk --skip xcode --skip vswin --skip vsmac --main

    - name: Install Xcode 12.4
      run: sudo xcode-select -s /Applications/Xcode_12.4.app

    - name: configure vsmac xcode
      run: |
        set -x
        mkdir -p ~/Library/Preferences/Xamarin
        rm -f ~/Library/Preferences/Xamarin/Settings.plist
        /usr/libexec/PlistBuddy -c "add :AppleSdkRoot string $(dirname $(dirname $(xcode-select -p)))" ~/Library/Preferences/Xamarin/Settings.plist || true
        cat ~/Library/Preferences/Xamarin/Settings.plist || true
   
    #- name: setup-xamarin
    #  uses: maxim-lobanov/setup-xamarin@v1
    #  with:
    #    mono-version: latest
    #    xamarin-ios-version: latest
    #    xamarin-mac-version: latest 
    #    xcode-version: 12.x 

    - name: Build App.Cross
      run: dotnet build ./Nivaes.App.Cross/ --configuration Release

    #- name: Restore iOS
    #  run: dotnet restore ./Nivaes.App.Cross.iOS/

    #- name: Build App.Cross.iOS
    #  run: msbuild ./Nivaes.App.Cross.iOS/ /t:build
    #  #run: dotnet build ./Nivaes.App.Cross.iOS/ --configuration Release

    #- name: Restore macCatalyst
    #  run: dotnet restore ./Nivaes.App.Cross.macCatalyst/

    #- name: Build App.Cross.macCatalyst
    #  run: msbuild ./Nivaes.App.Cross.macCatalyst/ /t:build
    #  #run: dotnet build ./Nivaes.App.Cross.macCatalyst/ --configuration Release

    #- name: Restore macOS
    #  run: dotnet restore ./Nivaes.App.Cross.macOS/

    #- name: Build App.Cross.macOS
    #  run: msbuild ./Nivaes.App.Cross.macOS/ /t:build
    ##  run: dotnet build ./Nivaes.App.Cross.macOS/ --configuration Release

    #- name: Restore watchOS
    #  run: dotnet restore ./Nivaes.App.Cross.watchOS/

    #- name: Build App.Cross.watchOS
    #  run: msbuild ./Nivaes.App.Cross.watchOS/ /t:build
    #  #run: dotnet build ./Nivaes.App.Cross.watchOS/ --configuration Release

    #- name: Restore tvOS
    #  run: dotnet restore ./Nivaes.App.Cross.tvOS/

    #- name: Build App.Cross.tvOS
    #  run: msbuild ./Nivaes.App.Cross.tvOS/ /t:build
    #  #run: dotnet build ./Nivaes.App.Cross.tvOS/ --configuration Release

  build-Windows:
    needs: build
    runs-on: windows-2019

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Checkout
      uses: actions/checkout@v2

    #- name: Setup .NET Core 3.1.x
    #  uses: actions/setup-dotnet@v1
    #  with:
    #    dotnet-version: 3.1.x

    #- name: Setup .NET Core 5.0.x
    #  uses: actions/setup-dotnet@v1
    #  with:
    #    dotnet-version: 5.0.x
    #    source-url: https://nuget.pkg.github.com/Nivaes/index.json
    #  env:
    #    NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    #- name: Setup .NET Core 6.0.x
    #  uses: actions/setup-dotnet@v1
    #  with:
    #    dotnet-version: 6.0.100-preview.44.21255.9
    #    source-url: https://nuget.pkg.github.com/Nivaes/index.json
    #  env:
    #    NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Setup .NET Core 6.0.x
      run: |
        Invoke-WebRequest -Uri "https://dot.net/v1/dotnet-install.ps1" -OutFile dotnet-install.ps1
        .\dotnet-install.ps1 -Version 6.0.100-preview.6.21354.2 -InstallDir "$env:ProgramFiles\dotnet\" -Verbose
        dotnet --list-sdks

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build App.Cross
      run: dotnet build ./Nivaes.App.Cross/ --framework netstandard2.1 --configuration Release

    - name: Restore Windows
      run: dotnet restore ./Nivaes.App.Cross.Windows/

    - name: Build Windows
      run: msbuild ./Nivaes.App.Cross.Windows/ /t:build
    #  run: dotnet build ./Nivaes.App.Cross.Windows/ --configuration Release

    - name: Build Wpf
      run: dotnet build ./Nivaes.App.Cross.Windows.Wpf/ --configuration Release
