name: CI

on:
  push:
    branches-ignore:
    - 'release/**'
    paths-ignore:
    - '**/*.md'
  pull_request:
    types: [opened, synchronize, reopened] 
    paths-ignore:
    - '**/*.md'

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET Core 3.1.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Setup .NET Core 5.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        source-url: https://nuget.pkg.github.com/Nivaes/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Setup .NET Core 6.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100-preview.1.21103.13

    - name: Build.App.Cross
      run: dotnet build ./Nivaes.App.Cross/ --configuration Release

    #- name: Test
    #  run: dotnet test --configuration Release --no-build --verbosity normal

  build-Android:
    needs: build
    runs-on: ubuntu-20.04

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET Core 3.1.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Setup .NET Core 5.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        source-url: https://nuget.pkg.github.com/Nivaes/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Setup .NET Core 6.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100-preview.1.21103.13

    - name: setup-xamarin
      uses: maxim-lobanov/setup-xamarin@v1
      with:
        mono-version: latest
        xamarin-android-version: latest

    - name: Build App.Cross
      run: dotnet build ./Nivaes.App.Cross/ --framework netstandard2.1 --configuration Release

    - name: Build Droid
      run: dotnet build ./Nivaes.App.Cross.Droid/ --configuration Release

    - name: Build WatchOS
      run: dotnet build ./Nivaes.App.Cross.watchOS/ --configuration Release

  build-MacOs:
    needs: build
    runs-on: macos-11.0

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET Core 3.1.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Setup .NET Core 5.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        source-url: https://nuget.pkg.github.com/Nivaes/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Setup .NET Core 6.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100-preview.1.21103.13

    - name: setup-xamarin
      uses: maxim-lobanov/setup-xamarin@v1
      with:
        mono-version: latest
        xamarin-ios-version: latest
        xamarin-mac-version: latest 
        xcode-version: 12.x 

    - name: Build App.Cross
      run: dotnet build ./Nivaes.App.Cross/ --framework netstandard2.1 --configuration Release

    - name: Build iOS
      run: dotnet build ./Nivaes.App.Cross.iOS/ --configuration Release

    - name: Build MacCatalyst
      run: dotnet build ./Nivaes.App.Cross.macCatalyst/ --configuration Release

    - name: Build MacOS
      run: dotnet build ./Nivaes.App.Cross.macOS/ --configuration Release

    - name: Build TvOS
      run: dotnet build ./Nivaes.App.Cross.tvOS/ --configuration Release

  build-Windows:
    needs: build
    runs-on: windows-2019

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET Core 3.1.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Setup .NET Core 5.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        source-url: https://nuget.pkg.github.com/Nivaes/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Setup .NET Core 6.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100-preview.1.21103.13

    - name: Build App.Cross
      run: dotnet build ./Nivaes.App.Cross/ --framework netstandard2.1 --configuration Release

    - name: Build Windows
      run: dotnet build ./Nivaes.App.Cross.Windows/ --configuration Release

    - name: Build Wpf
      run: dotnet build ./Nivaes.App.Cross.Windows.Wpf/ --configuration Release
