name: CI

on:
  push:
    branches-ignore:
    - 'release/v**'
    paths-ignore:
    - '**/*.md'
    - '**/*.sln'
  pull_request:
    #types: [opened, synchronize, reopened]
    types: [synchronize]
    paths-ignore:
    - '**/*.md'
    - '**/*.sln'

permissions:
  contents: read
  packages: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-app-cross-core:
     uses: ./.github/workflows/workflow_call_build_core.yaml
  
  build-app-cross-android:
    needs: build-app-cross-core
    uses: ./.github/workflows/workflow_call_build_android.yaml  

  build-app-cross-android-sample:
    needs: build-app-cross-android
    uses: ./.github/workflows/workflow_call_build_android-sample.yaml  

  build-app-cross-macos:
    needs: build-app-cross-core
    uses: ./.github/workflows/workflow_call_build_macos.yaml  

  # build-app-cross-macos-samples:
  #   needs: build-app-cross-ios
  #   uses: ./.github/workflows/workflow_call_build_macos-sample.yaml  

  build-app-cross-ios:
    needs: build-app-cross-core
    uses: ./.github/workflows/workflow_call_build_ios.yaml  

  build-app-cross-ios-samples:
    needs: build-app-cross-ios
    uses: ./.github/workflows/workflow_call_build_ios_sample.yaml  

  build-app-cross-WinUI:
    needs: build-app-cross-core
    uses: ./.github/workflows/workflow_call_build_winui.yaml 
    
  build-app-cross-WinUI-samples:
    needs: build-app-cross-WinUI
    uses: ./.github/workflows/workflow_call_build_winui_sample.yaml

  build-app-cross-web:
    needs: build-app-cross-core
    uses: ./.github/workflows/workflow_call_build_web.yaml
             
  build-app-cross-web-samples:
    needs: build-app-cross-web
    uses: ./.github/workflows/workflow_call_build_web_sample.yaml