name: CI

on:
  push:
    branches-ignore:
    - 'release/**'
    paths-ignore:
    - '**/*.md'
    - 'Samples/**'
  pull_request:
    types: [opened, synchronize, reopened] 
    paths-ignore:
    - '**/*.md'
    - 'Samples/**'

env:
    net_core_version: 6.0.100-preview.6.21355.2

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET Core 6.0.x
      uses: actions/setup-dotnet@v1 
      with:
        dotnet-version: ${{ env.net_core_version }}
        source-url: https://nuget.pkg.github.com/Nivaes/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Build.App.Cross
      run: dotnet build ./Nivaes.App.Cross/ --configuration Release

    #- name: Test
    #  run: dotnet test --configuration Release --no-build --verbosity normal

  build-Android:
    needs: build
    runs-on: windows-2019
    #runs-on: ubuntu-20.04

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET Core 6.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.net_core_version }}

    - name: Install workload
      shell: pwsh
      run: |
        dotnet workload install maui-android
        dotnet workload install microsoft-android-sdk-full

    - name: Build App.Cross
      run: dotnet build ./Nivaes.App.Cross/ --framework netstandard2.1 --configuration Release

    - name: Build App.Cross.Droid 
      run: dotnet build ./Nivaes.App.Cross.Droid/ --configuration Release

  build-MacOs:
    needs: build
    runs-on: macos-10.15

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET Core 6.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.net_core_version }}
        source-url: https://nuget.pkg.github.com/Nivaes/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Install workload
      shell: pwsh
      run: |
        dotnet workload install maui-ios
        dotnet workload install maui-maccatalyst
        #dotnet workload install microsoft-ios-sdk-full
        #dotnet workload install microsoft-maccatalyst-sdk-full
        #dotnet workload install microsoft-macos-sdk-full
        #dotnet workload install microsoft-tvos-sdk-full

    - name: Install Xcode
      uses: devbotsxyz/xcode-select@v1

    - name: configure vsmac xcode
      run: |
        set -x
        mkdir -p ~/Library/Preferences/Xamarin
        rm -f ~/Library/Preferences/Xamarin/Settings.plist
        /usr/libexec/PlistBuddy -c "add :AppleSdkRoot string $(dirname $(dirname $(xcode-select -p)))" ~/Library/Preferences/Xamarin/Settings.plist || true
        cat ~/Library/Preferences/Xamarin/Settings.plist || true
   
    - name: Build App.Cross
      run: dotnet build ./Nivaes.App.Cross/ --configuration Release

    #- name: Restore iOS
    #  run: dotnet restore ./Nivaes.App.Cross.iOS/

    - name: Build App.Cross.iOS
      run: dotnet build ./Nivaes.App.Cross.iOS/ --configuration Release

    #- name: Restore macCatalyst
    #  run: dotnet restore ./Nivaes.App.Cross.macCatalyst/

    #- name: Build App.Cross.macCatalyst  
    #  run: dotnet build ./Nivaes.App.Cross.macCatalyst/ --configuration Release

    #- name: Restore macOS
    #  run: dotnet restore ./Nivaes.App.Cross.macOS/

    - name: Build App.Cross.macOS
      run: dotnet build ./Nivaes.App.Cross.macOS/ --configuration Release

    #- name: Restore watchOS
    #  run: dotnet restore ./Nivaes.App.Cross.watchOS/

    #- name: Build App.Cross.watchOS
    #  run: msbuild ./Nivaes.App.Cross.watchOS/ /t:build
    #  #run: dotnet build ./Nivaes.App.Cross.watchOS/ --configuration Release

    #- name: Restore tvOS
    #  run: dotnet restore ./Nivaes.App.Cross.tvOS/

    #- name: Build App.Cross.tvOS
    #  run: msbuild ./Nivaes.App.Cross.tvOS/ /t:build
    #  #run: dotnet build ./Nivaes.App.Cross.tvOS/ --configuration Release

  build-Windows:
    needs: build
    runs-on: windows-2019

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET Core 6.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.net_core_version }} 
        source-url: https://nuget.pkg.github.com/Nivaes/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build App.Cross
      run: dotnet build ./Nivaes.App.Cross/ --framework netstandard2.1 --configuration Release

    #- name: Restore Windows
    #  run: dotnet restore ./Nivaes.App.Cross.Windows/

    - name: Build Windows
      run: dotnet build ./Nivaes.App.Cross.Windows/ --configuration Release

    - name: Build Wpf
      run: dotnet build ./Nivaes.App.Cross.Windows.Wpf/ --configuration Release
