name: ci android aot

on:
  push:
    paths:
    - '.github/workflows/ci_android_aot.yaml'
    - 'samples/Nivaes.App.Cross.Sample.Droid'
  pull_request:
    #types: [opened, synchronize, reopened]
    types: [synchronize]
    paths-ignore:
    - '**/*.md'
    - '**/*.sln'

jobs:
  publish-ample-client-android:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: ./global.json
        source-url: https://nuget.pkg.github.com/Nivaes/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Install workload
      run: |
        dotnet workload install android

    - name: Install Java SDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Restore Dependencies
      run: |
       dotnet restore ./samples/Nivaes.App.Cross.Sample.Droid/

    - name: Build
      run: |
       dotnet build ./samples/Nivaes.App.Cross.Sample.Droid/ --configuration Release --no-restore

    - name: Publish
      run: |
        dotnet publish ./samples/Nivaes.App.Cross.Sample.Droid/ --configuration Release --no-restore --no-restore --framework net9.0-android -p:PublishAot=true
    #     dotnet publish --framework net9.0-android --configuration Release -p:AndroidKeyStore=true -p:AndroidSigningKeyStore=myapp.keystore -p:AndroidSigningKeyAlias=myapp -p:AndroidSigningKeyPass=mypassword -p:AndroidSigningStorePass=mypassword

  
