name: Build Cross PWA

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Checkout
      uses: actions/checkout@v5

    - name: Setup PWA
      uses: ./.github/actions/setup-PWA
      with:
        global-json-file: ./global.json

    - name: Restore Dependencies
      run: |
          dotnet restore Sources/Nivaes.App.Cross.PWA.SourceGenerator --configfile .github/NuGet.config
          dotnet restore Sources/Nivaes.App.Cross.PWA --configfile .github/NuGet.config
          dotnet restore Samples/Nivaes.App.Cross.Sample.PWA/Nivaes.App.Cross.Sample.PWA.Client --configfile .github/NuGet.config
          dotnet restore Samples/Nivaes.App.Cross.Sample.PWA/Nivaes.App.Cross.Sample.PWA --configfile .github/NuGet.config
      env:
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                 
    - name: Build Web Client
      run: |
          dotnet build Samples/Nivaes.App.Cross.Sample.PWA/Nivaes.App.Cross.Sample.PWA.Client \
            --configuration Release \
            --no-restore 

    - name: Build Web
      run: |
          dotnet build Samples/Nivaes.App.Cross.Sample.PWA/Nivaes.App.Cross.Sample.PWA \
            --configuration Release \
            --no-restore 

    # - name: publish
    #   run: |
    #     dotnet publish Samples/Nivaes.App.Cross.Sample.PWA/Nivaes.App.Cross.Sample.PWA \
    #         --property:PublishTrimmed=true \
    #         --configuration Release \
    #         --no-restore --no-build