name: Build Cross MascOS Sample

on:
  workflow_call:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Checkout
      uses: actions/checkout@v5

    - uses: ./.github/actions/setup-xcode
      with:
        global-json-file: ./global.json

    - uses: ./.github/actions/setup-xcode
      with:
        global-json-file: ./global.json

    # - name: Restore Dependencies
    #   run: |
    #       dotnet restore sources/Nivaes.App.Cross.AppKit --configfile .github/NuGet.config --runtime osx-arm64
    #       dotnet restore sources/Nivaes.App.Cross.AppKit --configfile .github/NuGet.config --runtime osx-x64
    #       dotnet restore sources/Nivaes.App.Cross.AppKit.SourceGenerator --configfile .github/NuGet.config 
    #       dotnet restore samples/Nivaes.App.Cross.Sample.AppKit.MacOS --configfile .github/NuGet.config --runtime osx-arm64
    #       dotnet restore samples/Nivaes.App.Cross.Sample.AppKit.MacOS --configfile .github/NuGet.config --runtime osx-x64

    - name: Restore Dependencies
      run: |
          dotnet restore sources/Nivaes.App.Cross.AppKit --configfile .github/NuGet.config
          dotnet restore sources/Nivaes.App.Cross.AppKit.SourceGenerator --configfile .github/NuGet.config 
          dotnet restore samples/Nivaes.App.Cross.Sample.AppKit.MacOS --configfile .github/NuGet.config

      env:
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Build
      run: |
          dotnet build samples/Nivaes.App.Cross.Sample.AppKit.MacOS --property:RunAOTAnalysis=true --runtime osx-arm64 --configuration Release --verbosity normal --no-restore
    
    - name: Publish
      run: |
          dotnet publish samples/Nivaes.App.Cross.Sample.AppKit.MacOS \
            --runtime ios-arm64 \
            --configuration Release\
            --verbosity normal --no-restore --no-build \
            --property:RuntimeIdentifiers="osx-x64;osx-arm64"