name: Build Cross Android Sample

on:
  workflow_call:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Checkout
      uses: actions/checkout@v5

    - name: Setup Android SDK
      uses: ./.github/actions/setup-android
      with:
        global-json-file: ./global.json

    - name: Restore Dependencies
      run: |
          dotnet restore Sources/Nivaes.App.Cross.Droid.SourceGenerator --configfile .github/NuGet.config
          dotnet restore Sources/Nivaes.App.Cross.Droid --configfile .github/NuGet.config
          dotnet restore Samples/Nivaes.App.Cross.Sample.Droid --configfile .github/NuGet.config
          # dotnet restore Sources/Nivaes.App.Cross.Droid --configfile .github/NuGet.config --runtime android-x64
          # dotnet restore Sources/Nivaes.App.Cross.Droid --configfile .github/NuGet.config --runtime android-arm64
          # dotnet restore Samples/Nivaes.App.Cross.Sample.Droid --configfile .github/NuGet.config --runtime android-x64
          # dotnet restore Samples/Nivaes.App.Cross.Sample.Droid --configfile .github/NuGet.config --runtime android-arm64
      env:
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                   
    - name: Build
      run: |
          dotnet build Samples/Nivaes.App.Cross.Sample.Droid \
            --property:AndroidPackageFormat=aab \
            --configuration Release \
            --no-restore

    - name: publish
      run: |
        dotnet publish Samples/Nivaes.App.Cross.Sample.Droid \
            --property:AndroidPackageFormat=aab \
            --configuration Release \
            --no-restore