name: Build Cross Android

on:
  workflow_call:

jobs:
  build:
    strategy:
      matrix:
        include:
          - runner: windows-2025-vs2026
            rid: win-x64
            platform: x64
          - runner: windows-11-vs2026-arm
            rid: win-arm64
            platform: ARM64

    runs-on: ${{ matrix.runner }}

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Checkout
      uses: actions/checkout@v5

    - uses: ./.github/actions/setup-WinUI
      with:
        global-json-file: ./global.json

    - name: Restore Dependencies
      run: |
          dotnet build Sources/Nivaes.App.Cross --configfile .github/NuGet.config --runtime ${{ matrix.rid }} --property:PublishReadyToRun=true
          dotnet build Sources/Nivaes.App.Cross.SourceGenerator --configfile .github/NuGet.config --runtime ${{ matrix.rid }} --property:PublishReadyToRun=true
          dotnet restore Sources/Nivaes.App.Cross.WinUI --configfile .github/NuGet.config --runtime ${{ matrix.rid }} --property:PublishReadyToRun=true
          dotnet restore Sources/Nivaes.App.Cross.WinUI.SourceGenerator --configfile .github/NuGet.config --runtime ${{ matrix.rid }} --property:PublishReadyToRun=true
          dotnet restore Samples/Nivaes.App.Cross.Sample.WinUI --configfile .github/NuGet.config --runtime ${{ matrix.rid }} --property:PublishReadyToRun=true
      env:
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # - name: Build
    #   run: |
    #       dotnet build Sources/Nivaes.App.Cross.SourceGenerator --configuration Release --no-restore
    #       dotnet build Sources/Nivaes.App.Cross --property:RunAOTAnalysis=true --configuration Release --no-restore        

    # - name: Build and Package
    #   run: |
    #       msbuild Samples/Nivaes.App.Cross.Sample.WinUI `
    #       /p:Configuration=release `
    #       /p:GenerateAppxPackageOnBuild=true `
    #       /p:AppxBundlePlatforms="win-x64|win-arm64" `
    #       /p:AppxBundle=Always `
    #       /p:UapAppxPackageBuildMode=SideloadOnly

    - name: Build
      run: |
          dotnet build Samples/Nivaes.App.Cross.Sample.WinUI `
            --configuration Release `
            --property:RuntimeIdentifiers=${{ matrix.rid }} `
            --property:Platform=${{ matrix.platform }} `
            --property:GenerateAppxPackageOnBuild=true `
            --no-incremental `
            --verbosity normal

    # - name: Build-arm64
    #   run: |
    #       dotnet build Samples/Nivaes.App.Cross.Sample.WinUI `
    #         --configuration Release `
    #         --property:BuildProjectReferences=false `
    #         --property:RuntimeIdentifiers="win-arm64" `
    #         --property:Platform=arm64 `
    #         --property:GenerateAppxPackageOnBuild=true `
    #         --no-incremental `
    #         --verbosity normal

    # - name: Publish
    #   run: |
    #      msbuild samples\Nivaes.App.Cross.Sample.WinUI\Nivaes.App.Cross.Sample.WinUI.csproj `
    #           /t:Publish `
    #           /p:NoBuild=true `
    #           /p:Configuration=Release `
    #           /p:GenerateAppxPackageOnBuild=true `
    #           /p:AppxBundle=Always `
    #           /p:AppxBundlePlatforms="x64|ARM64" `
    #           /p:UapAppxPackageBuildMode=StoreUpload `
    #           /p:AppxPackageSigningEnabled=false

    - uses: actions/upload-artifact@v4
      with:
        name: WinUIStorePackage${{ matrix.platform }}
        path: |
          **\*.msix