name: Build Cross Core

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Checkout
      uses: actions/checkout@v5

    - name: setup-xcode 
      uses: ./.github/actions/setup-core
      with:
        global-json-file: ./global.json

    - name: Install workload
      run: |
        dotnet workload install android

    - name: Restore Dependencies
      run: |
          dotnet restore sources/Nivaes.App.Cross.SourceGenerator --configfile .github/NuGet.config
          dotnet restore sources/Nivaes.App.Cross --configfile .github/NuGet.config
      env:
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: bash

    - name: Build
      run: |
          dotnet build sources/Nivaes.App.Cross.SourceGenerator --configuration Release --no-restore
          dotnet build sources/Nivaes.App.Cross --configuration Release --property:RunAOTAnalysis=true --no-restore

    - name: Test
      run: |
          dotnet test sources/Nivaes.App.Cross.SourceGenerator --configuration Release --no-build --verbosity normal --no-restore
          dotnet test sources/Nivaes.App.Cross --configuration Release --no-build --verbosity normal --no-restore
          
    - name: Check-AotCompatible
      run: |
          dotnet publish sources/Nivaes.App.Cross --property:RunAOTAnalysis=true --framework net10.0 --configuration Release --no-restore --no-build