name: Build Cross Android

on:
  workflow_call:

jobs:
  build:
    strategy:
      matrix:
        include:
          - runner: windows-2025-vs2026
            rid: win-x64
            platform: x64
          - runner: windows-11-vs2026-arm
            rid: win-arm64
            platform: ARM64

    runs-on: ${{ matrix.runner }}

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Checkout
      uses: actions/checkout@v5

    - uses: ./.github/actions/setup-WinUI
      with:
        global-json-file: ./global.json

    - name: Restore Dependencies
      run: |
          dotnet build Sources/Nivaes.App.Cross --configfile .github/NuGet.config --runtime ${{ matrix.rid }} --property:PublishReadyToRun=true
          dotnet build Sources/Nivaes.App.Cross.SourceGenerator --configfile .github/NuGet.config --runtime ${{ matrix.rid }} --property:PublishReadyToRun=true
          dotnet restore Sources/Nivaes.App.Cross.WinUI --configfile .github/NuGet.config --runtime ${{ matrix.rid }} --property:PublishReadyToRun=true
          dotnet restore Sources/Nivaes.App.Cross.WinUI.SourceGenerator --configfile .github/NuGet.config --runtime ${{ matrix.rid }} --property:PublishReadyToRun=true
          dotnet restore Samples/Nivaes.App.Cross.Sample.WinUI --configfile .github/NuGet.config --runtime ${{ matrix.rid }} --property:PublishReadyToRun=true
      env:
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Build
      run: |
          dotnet build Samples/Nivaes.App.Cross.Sample.WinUI `
            --configuration Release `
            --property:RuntimeIdentifiers=${{ matrix.rid }} `
            --property:Platform=${{ matrix.platform }} `
            --property:GenerateAppxPackageOnBuild=true `
            --no-incremental `
            --verbosity normal

    - name: Prepare artifact
      shell: pwsh
      run: |
        New-Item -ItemType Directory -Force artifact | Out-Null

        Get-ChildItem -Recurse -Filter "*${{ matrix.platform }}.msix" |
          Copy-Item -Destination artifact

    - uses: actions/upload-artifact@v4
      with:
        name: msix-${{ matrix.platform }}
        path: artifact
  
  packet-bundle:
    needs: build
    runs-on: windows-2025-vs2026

    steps:

      - uses: actions/download-artifact@v4
        with:
          path: packages

      - name: Prepare bundle
        shell: pwsh
        run: |
          mkdir bundle

          Copy-Item packages\msix-x64\*.msix bundle
          Copy-Item packages\msix-ARM64\*.msix bundle

      - name: Locate MakeAppx
        id: sdk
        shell: pwsh
        run: |
          $makeappx = Get-ChildItem "C:\Program Files (x86)\Windows Kits\10\bin" `
                        -Recurse `
                        -Filter MakeAppx.exe |
                        Sort-Object FullName -Descending |
                        Select-Object -First 1

          echo "MAKEAPPX=$($makeappx.FullName)" >> $env:GITHUB_ENV

      - name: Create Bundle
        shell: pwsh
        run: |
          & "$env:MAKEAPPX" bundle `
              /d bundle `
              /p bundle\Nivaes.App.Cross.Sample.msixbundle

      - uses: actions/upload-artifact@v4
        with:
          name: msixbundle
          path: bundle/*.msixbundle
  