name: Build Cross iOS

on:
  workflow_call:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Checkout
      uses: actions/checkout@v5

    - name: setup-xcode 
      uses: ./.github/actions/setup-xcode
      with:
        global-json-file: ./global.json

    - name: Restore Dependencies
      run: |
          dotnet restore Sources/Nivaes.App.Cross.UIKit --configfile .github/NuGet.config
          dotnet restore Sources/Nivaes.App.Cross.UIKit.SourceGenerator --configfile .github/NuGet.config
      env:
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Build
      run: |
          dotnet build Sources/Nivaes.App.Cross.UIKit --property:RunAOTAnalysis=true --configuration Release --no-restore
          dotnet build Sources/Nivaes.App.Cross.UIKit.SourceGenerator --configuration Release --no-restore

    - name: Test
      run: |
          dotnet test Sources/Nivaes.App.Cross.UIKit --configuration Release --no-build --verbosity normal --no-restore
          dotnet test Sources/Nivaes.App.Cross.UIKit.SourceGenerator --configuration Release --no-build --verbosity normal --no-restore
