name: Build Cross Android

on:
  workflow_call:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Checkout
      uses: actions/checkout@v5

    - uses: ./.github/actions/setup-WinUI
      with:
        global-json-file: ./global.json

    - name: Restore Dependencies
      run: |
          dotnet restore Sources/Nivaes.App.Cross.WinUI --configfile .github/NuGet.config --runtime win-x64 --property:PublishReadyToRun=true
          dotnet restore Sources/Nivaes.App.Cross.WinUI --configfile .github/NuGet.config --runtime win-arm64 --property:PublishReadyToRun=true
          dotnet restore Sources/Nivaes.App.Cross.WinUI.SourceGenerator --configfile .github/NuGet.config --runtime win-x64 --property:PublishReadyToRun=true
          dotnet restore Sources/Nivaes.App.Cross.WinUI.SourceGenerator --configfile .github/NuGet.config --runtime win-arm64 --property:PublishReadyToRun=true
          dotnet restore Samples/Nivaes.App.Cross.Sample.WinUI --configfile .github/NuGet.config --runtime win-x64 --property:PublishReadyToRun=true
          dotnet restore Samples/Nivaes.App.Cross.Sample.WinUI --configfile .github/NuGet.config --runtime win-arm64 --property:PublishReadyToRun=true
      env:
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Build-x64
      run: |
          dotnet build Samples/Nivaes.App.Cross.Sample.WinUI `
            --configuration Release `
            --property:RuntimeIdentifiers="win-x64" `
            --property:Platform=x64 `
            --verbosity normal

    - name: Build-arm64
      run: |
          dotnet build Samples/Nivaes.App.Cross.Sample.WinUI `
            --configuration Release `
            --property:RuntimeIdentifiers="win-arm64" `
            --property:Platform=arm64 `
            --verbosity normal

    - name: Publish
      run: |
         msbuild samples\Nivaes.App.Cross.Sample.WinUI\Nivaes.App.Cross.Sample.WinUI.csproj `
              /p:Configuration=Release `
              /p:Platform=x64 `
              /p:GenerateAppxPackageOnBuild=true `
              /p:AppxBundle=Always `
              /p:AppxBundlePlatforms="x64|ARM64" `
              /p:UapAppxPackageBuildMode=StoreUpload `
              /p:AppxPackageSigningEnabled=false

    - uses: actions/upload-artifact@v4
      with:
        name: WinUIStorePackage
        path: |
          **/AppPackages/**