name: Build Cross Android Sample

on:
  workflow_call:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Checkout
      uses: actions/checkout@v5

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Restore Dependencies
      run: |
          dotnet restore sources/Nivaes.App.Cross.Droid.SourceGenerator --configfile .github/NuGet.config
          dotnet restore sources/Nivaes.App.Cross.Droid --configfile .github/NuGet.config
          dotnet restore samples/Nivaes.App.Cross.Sample.Droid --configfile .github/NuGet.config
          # dotnet restore sources/Nivaes.App.Cross.Droid --configfile .github/NuGet.config --runtime android-x64
          # dotnet restore sources/Nivaes.App.Cross.Droid --configfile .github/NuGet.config --runtime android-arm64
          # dotnet restore samples/Nivaes.App.Cross.Sample.Droid --configfile .github/NuGet.config --runtime android-x64
          # dotnet restore samples/Nivaes.App.Cross.Sample.Droid --configfile .github/NuGet.config --runtime android-arm64
      env:
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                   
    - name: Build
      run: |
          dotnet build samples/Nivaes.App.Cross.Sample.Droid \
            --property:AndroidPackageFormat=aab \
            --configuration Release \
            --no-restore

    - name: publish
      run: |
        dotnet publish samples/Nivaes.App.Cross.Sample.Droid \
            --property:AndroidPackageFormat=aab \
            --configuration Release \
            --no-restore