name: Build Cross PWA

on:
  workflow_call:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Checkout
      uses: actions/checkout@v5

    - name: Setup PWA
      uses: ./.github/actions/setup-PWA
      with:
        global-json-file: ./global.json

    - name: Restore Dependencies
      run: |
          dotnet restore Sources/Nivaes.App.Cross --configfile .github/NuGet.config
          dotnet restore Sources/Nivaes.App.Cross.SourceGenerator --configfile .github/NuGet.config
          dotnet restore Sources/Nivaes.App.Cross.PWA --configfile .github/NuGet.config
          dotnet restore Sources/Nivaes.App.Cross.PWA.SourceGenerator --configfile .github/NuGet.config
      env:
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Build
      run: |
          dotnet build Sources/Nivaes.App.Cross.PWA --property:RunAOTAnalysis=true --configuration Release --no-restore
          dotnet build Sources/Nivaes.App.Cross.PWA.SourceGenerator --configuration Release --no-restore

    # - name: Test
    #   run: |
    #       dotnet test Sources/Nivaes.App.Cross.PWA --configuration Release --no-build --verbosity normal --no-restore
    #       dotnet test Sources/Nivaes.App.Cross.PWA.SourceGenerator --configuration Release --no-build --verbosity normal --no-restore
