name: Build Cross WinUI

on:
  workflow_call:

jobs:
  build:
    runs-on: windows-2025-vs2026

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Checkout
      uses: actions/checkout@v5

    # - uses: ./.github/actions/setup-WinUI
    #   with:
    #     global-json-file: ./global.json

    - name: Restore Dependencies
      run: |
          dotnet restore Sources/Nivaes.App.Cross.WinUI --configfile .github/NuGet.config
          dotnet restore Sources/Nivaes.App.Cross.WinUI.SourceGenerator --configfile .github/NuGet.config
          dotnet restore Samples/Nivaes.App.Cross.Sample.WinUI --configfile .github/NuGet.config
      env:
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Build
      run: |
          dotnet build Sources/Nivaes.App.Cross.WinUI.SourceGenerator --configuration Release --no-restore
          dotnet build Sources/Nivaes.App.Cross.WinUI --property:RunAOTAnalysis=true --configuration Release --no-restore        

    - name: Test
      run: |
          dotnet test Sources/Nivaes.App.Cross.WinUI.SourceGenerator --configuration Release --no-build --verbosity normal --no-restor
          dotnet test Sources/Nivaes.App.Cross.WinUI --configuration Release --no-build --verbosity normal --no-restore
          